#line 2 "cool-lex.cc"

#line 4 "cool-lex.cc"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

/* %not-for-header */

/* %if-c-only */
/* %if-not-reentrant */

/* %endif */
/* %endif */
/* %ok-for-header */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* %if-c++-only */
/* %endif */

/* %if-c-only */
    
/* %endif */

/* %if-c-only */

/* %endif */

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
/* %if-c-only */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>
/* %endif */

/* %if-tables-serialization */
/* %endif */
/* end standard C headers. */

/* %if-c-or-c++ */
/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* %endif */

/* %if-c++-only */
/* %endif */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* %not-for-header */

/* Returned upon end-of-file. */
#define YY_NULL 0
/* %ok-for-header */

/* %not-for-header */

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)
/* %ok-for-header */

/* %if-reentrant */
/* %endif */

/* %if-not-reentrant */

/* %endif */

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

/* %if-not-reentrant */
extern int yyleng;
/* %endif */

/* %if-c-only */
/* %if-not-reentrant */
extern FILE *yyin, *yyout;
/* %endif */
/* %endif */

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
/* %if-c-only */
	FILE *yy_input_file;
/* %endif */

/* %if-c++-only */
/* %endif */

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */

/* %if-not-reentrant */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */
/* %endif */
/* %ok-for-header */

/* %endif */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* %if-c-only Standard (non-C++) definition */

/* %if-not-reentrant */
/* %not-for-header */

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;
/* %ok-for-header */

/* %endif */

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

/* %endif */

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* %% [1.0] yytext/yyin/yyout/yy_state_type/yylineno etc. def's & init go here */

#define FLEX_DEBUG

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

/* %if-c-only Standard (non-C++) definition */

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* %endif */

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
/* %% [2.0] code to fiddle yytext and yyleng for yymore() goes here \ */\
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
/* %% [3.0] code to copy yytext_ptr to yytext[] goes here, if %array \ */\
	(yy_c_buf_p) = yy_cp;

/* %% [4.0] data tables for the DFA and the user's section 1 definitions go here */
#define YY_NUM_RULES 73
#define YY_END_OF_BUFFER 74
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[353] =
    {   0,
        0,    0,    0,    0,    5,    5,    2,    2,   74,   72,
       69,   70,   36,   54,   55,   51,   49,   64,   50,   61,
       52,   48,   60,   53,   63,   67,   62,   66,   72,   72,
       72,   72,   72,   72,   72,   72,   72,   72,   72,   58,
       59,   72,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   56,   72,   57,   65,   71,   47,   38,
       37,   73,    5,    8,    5,    7,    2,    3,   69,    4,
       11,   64,    1,   48,   60,   53,   13,   14,   12,   62,
       66,   34,   34,   34,    0,   34,   34,    0,   17,   17,
       18,   19,   34,   18,   34,   34,    0,   34,   34,    0,

       28,   28,   34,    0,   34,    0,   34,    0,   68,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       17,   35,   17,   17,   18,   19,   35,   18,   19,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   28,   28,
       35,   35,   35,   35,   35,   35,    0,   35,   35,    0,
        0,   18,    0,    0,   19,    0,    0,   17,   65,   47,
       46,   39,   40,   44,   45,   41,   43,   42,    5,    6,
        7,    9,    7,    2,   34,    0,   34,    0,    0,   34,
        0,   34,    0,    0,   34,    0,   34,    0,    0,   21,
       21,   34,    0,   21,   29,   29,   31,   31,   29,   34,

        0,   34,    0,   34,    0,   35,   35,   35,   35,   35,
       35,   35,   35,   35,    0,   35,   35,   35,   35,   35,
       21,   35,   21,   35,   29,   31,   29,   31,   35,   35,
       35,   35,    0,   35,   35,    0,   35,   35,   21,    0,
        0,    0,   31,    0,    0,    0,   21,   21,   39,   40,
        0,    9,   26,   26,   34,    0,   26,   16,   16,   27,
       27,   16,   34,    0,   34,    0,    0,   22,   22,   23,
       23,   24,   24,   34,    0,   26,   35,   26,   35,   16,
       27,   16,   27,   35,    0,   35,   35,   35,   35,   35,
       22,   22,   23,   23,   24,   32,   32,   24,   32,   24,

       35,   35,   24,   16,   22,   27,   27,   16,   16,   23,
       16,   39,   10,   15,   15,   34,    0,   34,    0,    0,
       25,   25,   15,   15,   33,   33,   33,   35,   35,   35,
       35,   25,   25,   15,   34,    0,   30,   30,   30,   35,
       30,   35,   30,   34,    0,   35,   35,   20,   20,   20,
       20,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    1,    1,    1,    1,    1,    5,
        6,    7,    8,    9,   10,   11,   12,   13,   13,   13,
       13,   13,   13,   13,   13,   14,   14,   15,   16,   17,
       18,   19,    1,   20,   21,   22,   23,   24,   25,   26,
       22,   27,   28,   22,   22,   29,   22,   30,   31,   32,
       22,   33,   34,   35,   36,   37,   38,   22,   22,   22,
       39,   40,   41,    1,   42,    1,   43,   44,   45,   46,

       47,   48,   49,   50,   51,   49,   49,   52,   49,   53,
       54,   55,   49,   56,   57,   58,   59,   60,   61,   49,
       49,   49,   62,   63,   64,   65,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[67] =
    {   0,
        1,    1,    2,    3,    1,    1,    4,    1,    1,    1,
        1,    1,    5,    5,    1,    1,    1,    1,    1,    1,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    1,    3,
        1,    5,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    1,    1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[363] =
    {   0,
        0,    0,   64,   66,   68,   69,  340,  331,  329, 1025,
      298, 1025, 1025,  257, 1025,  253, 1025,  244,  222, 1025,
     1025,   64,  210,  206,   69,  200,  197,  163,    0,   59,
       55,   54,   66,   78,   90,   65,   70,   89,   93, 1025,
     1025,    0,  144,  185,   97,  187,  183,  195,  198,   82,
       96,  191,  194, 1025,  241, 1025,   97, 1025,    0, 1025,
     1025,  263,    0, 1025,  148,   79,    0, 1025,  149, 1025,
     1025,  139, 1025,   80,  125,  120, 1025, 1025, 1025,   91,
       79,    0,  176,  121,  222,  217,  164,  239,    0, 1025,
        0,  236,  218,  260,  255,  252,  270,  100,  268,  274,

        0, 1025,  286,  291,  283,  289,  297,  299, 1025,  320,
        0,  325,  340,  350,  365,  353,  368,  357,  369,  363,
        0,  366,    0,  367,    0,  371,  362,    0,  373,  364,
      382,  402,  400,  406,  401,  403,  409,  413,    0,    0,
      419,  420,  421,  416,  430,  431,  453,  429,  457,  447,
      460, 1025,  477,  488,  464,  472,  476,  531,   30,    0,
     1025,   84,  121, 1025, 1025, 1025, 1025, 1025,    0, 1025,
      140,   83,  205,    0,  486,  490,  491,  498,  513,  516,
      517,  527,  548,  550,  552,  558,  553,  555,  573,    0,
     1025,  568,  569,  570,    0, 1025,    0, 1025, 1025,  567,

      574,  504,  576,  583,  588,  597,  600,  603,  604,  617,
      620,  622,  625,  611,  615,  618,  629,  628,  630,  640,
        0,  624,    0,  641,    0,    0,    0,    0,  655,  657,
      659,  670,  672,  660,  674,  681,  673,  679, 1025,  686,
      707,  695,  711,  722,  723,  726, 1025,  767,  221,  325,
       77, 1025,    0, 1025,  714,  718,  721,    0, 1025,    0,
     1025, 1025,  732,  746,  731,  755,  772,    0, 1025,    0,
     1025,    0, 1025,  744,  768,    0,  753,    0,  769,    0,
        0,    0,    0,  786,  792,  800,  771,  785,  796,  809,
        0,    0,    0,    0,    0,    0, 1025,    0,    0, 1025,

      815,  817,  818,  804, 1025,  822,  811, 1025,  813,  819,
      858,  328,   74,    0, 1025,  826,  843,  833,  864,  871,
        0, 1025,    0,    0,    0, 1025,    0,  856,  866,  865,
      874,    0,    0,  880,  867,  878,    0, 1025,  888,  889,
        0,  897,    0,  899,  901,  904,  906,    0, 1025,    0,
        0, 1025,  969,  975,  981,  983,  989,  994, 1000, 1006,
     1012, 1018
    } ;

static yyconst flex_int16_t yy_def[363] =
    {   0,
      352,    1,  353,  353,  354,  354,  355,  355,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  356,  356,
      356,  356,  356,  356,  356,  356,  356,  356,  356,  352,
      352,  357,  352,   43,   43,   43,   43,   43,   43,   43,
       43,   43,   43,  352,  352,  352,  352,  352,  358,  352,
      352,  359,  360,  352,  360,  361,  362,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  356,  356,  356,  352,  356,  356,  352,  356,  352,
      356,  356,  356,  352,  356,  356,  352,  356,  356,  352,

      356,  352,  356,  352,  356,  352,  356,  352,  352,   43,
       43,  110,  110,   43,   43,  110,  110,   43,   43,  110,
      110,   43,   43,  352,  110,  110,  110,   43,   43,   43,
      110,  110,   43,   43,  110,  110,   43,   43,  110,   43,
      110,   43,  110,  110,   43,   43,  352,  110,   43,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  358,
      352,  352,  352,  352,  352,  352,  352,  352,  360,  352,
      361,  352,  361,  362,  356,  352,  356,  352,  352,  356,
      352,  356,  352,  352,  356,  352,  356,  352,  352,  356,
      352,  356,  352,  352,  356,  352,  356,  352,  352,  356,

      352,  356,  352,  356,  352,  110,  110,   43,   43,  110,
      110,   43,   43,  110,  352,   43,  110,  110,   43,   43,
      110,  110,   43,   43,  110,  110,   43,   43,  110,   43,
      110,  110,  352,   43,   43,  352,  110,   43,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  356,  352,  356,  352,  352,  356,  352,  356,
      352,  352,  356,  352,  356,  352,  352,  356,  352,  356,
      352,  356,  352,  356,  352,  110,  110,   43,   43,  110,
      110,   43,   43,  110,  352,   43,  110,  110,   43,   43,
      110,   43,  110,   43,  110,  110,  352,   43,   43,  352,

      110,   43,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  356,  352,  356,  352,  356,  352,  352,
      356,  352,  110,   43,  110,  352,   43,  110,  110,   43,
       43,  110,   43,  352,  356,  352,  356,  352,  352,  110,
      110,   43,   43,  356,  352,  110,   43,  356,  352,  110,
       43,    0,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352
    } ;

static yyconst flex_int16_t yy_nxt[1092] =
    {   0,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       20,   21,   22,   22,   23,   24,   25,   26,   27,   28,
       29,   29,   30,   29,   31,   32,   29,   33,   34,   35,
       36,   37,   29,   29,   38,   29,   29,   39,   40,   10,
       41,   42,   43,   43,   44,   43,   45,   46,   43,   43,
       47,   48,   49,   50,   51,   43,   43,   52,   43,   43,
       53,   54,   55,   56,   57,   58,   60,   61,   60,   61,
       64,   64,   65,   65,   66,   66,   74,   74,   77,   83,
      251,   89,  313,   86,  172,  173,   78,   84,   87,  251,
      101,   91,   74,   74,  159,   92,  249,  250,   81,   93,

      103,   83,   95,   62,   89,   62,   86,  139,   96,   80,
       84,   87,  101,   91,   98,  105,   90,   88,   92,  107,
       99,   85,   93,  103,   95,  116,  141,  102,   94,  140,
      117,   96,  104,  250,  250,   76,   98,  195,  105,   75,
       97,  177,  107,   99,  102,  352,  352,   72,  118,  142,
       69,  106,  100,  119,  170,  108,  110,  110,  104,   88,
      195,  159,  196,  177,  110,  110,  110,  110,  110,  110,
      110,  110,  110,  110,  110,  110,  110,  110,  110,  110,
      110,  110,   81,  178,  182,  110,  111,  111,  111,  111,
      111,  111,  111,  111,  111,  111,  111,  111,  111,  111,

      111,  111,  111,  111,  111,  112,  182,  120,  125,  175,
      252,  173,  126,  113,  121,   80,  127,  143,   79,  131,
      148,   76,  135,  144,   75,  132,  183,  114,  136,  122,
      128,   73,  175,  312,  250,  129,  115,  123,  176,  130,
      145,  133,  178,  149,  137,   94,  146,   85,  134,  124,
      180,  138,   72,  147,  187,  176,  108,   97,   71,  183,
      100,  150,  185,   70,  178,  151,  152,  153,   90,  154,
      155,  156,  181,  180,  157,  162,  163,  187,  176,  181,
      188,  183,  192,  150,  179,  185,  186,  151,  152,  190,
      153,   90,  154,  155,  156,  181,  188,  157,  186,   69,

      193,  184,  197,  158,  191,  192,  164,  202,  198,  186,
      165,  196,  190,  203,  193,  166,  200,  191,  167,  188,
      168,  201,  189,  193,  204,  197,  205,  191,  352,  202,
      198,  198,  194,   68,  196,  203,  199,  250,  250,  200,
      250,  250,   68,  352,  201,  203,  352,  204,  201,  205,
      352,  203,  352,  201,  352,  352,  352,  352,  206,  205,
      207,  205,  110,  110,  110,  110,  110,  110,  110,  110,
      110,  110,  110,  110,  110,  110,  110,  110,  110,  110,
      110,  206,  207,  206,  352,  207,  210,  176,  211,  211,
      210,  214,  352,  352,  214,  215,  352,  217,  218,  217,

      218,  352,  178,  352,  352,  352,  208,  209,  352,  210,
      211,  213,  176,  212,  214,  181,  221,  216,  215,  181,
      217,  218,  219,  220,  188,  215,  188,  178,  215,  215,
      183,  183,  222,  186,  221,  186,  222,  226,  225,  221,
      352,  352,  352,  352,  191,  231,  225,  226,  352,  229,
      229,  232,  352,  352,  231,  222,  237,  223,  352,  224,
      226,  225,  191,  196,  193,  198,  232,  231,  193,  227,
      228,  196,  229,  230,  232,  198,  234,  203,  233,  237,
      176,  201,  201,  203,  237,  352,  352,  352,  233,  235,
      186,  205,  203,  233,  191,  352,  183,  196,  352,  203,

      352,  203,  242,  176,  205,  352,  198,  238,  178,  176,
      253,  233,  188,  186,  254,  236,  352,  191,  183,  205,
      196,  181,  239,  203,  255,  242,  186,  205,  352,  198,
      178,  256,  253,  272,  243,  188,  254,  254,  244,  240,
      258,  259,  352,  352,  181,  352,  256,  255,  254,  260,
      241,  245,  254,  256,  256,  203,  272,  186,  205,  254,
      256,  242,  258,  259,  246,  247,  273,  188,  196,  256,
      261,  260,  261,  245,  259,  257,  263,  203,  259,  259,
      186,  205,  264,  265,  242,  266,  352,  246,  247,  261,
      188,  196,  261,  248,  261,  270,  259,  264,  263,  268,

      269,  269,  271,  266,  264,  273,  265,  352,  266,  352,
      261,  274,  262,  352,  264,  266,  275,  266,  270,  264,
      264,  276,  268,  269,  269,  271,  266,  276,  273,  271,
      269,  269,  269,  277,  274,  267,  271,  277,  273,  275,
      352,  280,  281,  276,  284,  275,  280,  281,  285,  278,
      275,  284,  352,  287,  287,  291,  277,  352,  288,  254,
      279,  352,  256,  280,  281,  254,  256,  284,  282,  283,
      288,  285,  291,  285,  286,  287,  289,  285,  291,  259,
      285,  288,  261,  293,  259,  293,  269,  261,  295,  295,
      266,  264,  264,  290,  296,  292,  297,  352,  296,  352,

      352,  301,  266,  269,  352,  297,  293,  301,  294,  352,
      273,  295,  298,  352,  275,  273,  296,  271,  297,  271,
      299,  273,  273,  271,  301,  352,  269,  297,  352,  352,
      302,  259,  297,  273,  297,  275,  297,  275,  273,  271,
      256,  275,  269,  300,  261,  261,  271,  314,  303,  269,
      308,  315,  266,  259,  315,  352,  256,  305,  318,  352,
      352,  352,  271,  256,  316,  269,  261,  261,  321,  304,
      314,  352,  308,  305,  315,  266,  315,  315,  317,  256,
      315,  318,  319,  315,  306,  307,  323,  316,  308,  261,
      321,  309,  322,  319,  317,  310,  273,  266,  269,  319,

      256,  317,  323,  328,  317,  319,  322,  352,  317,  323,
      325,  261,  329,  309,  322,  315,  326,  319,  310,  273,
      266,  269,  319,  256,  325,  324,  328,  317,  328,  311,
      322,  315,  325,  317,  320,  329,  329,  315,  326,  332,
      352,  332,  322,  322,  315,  317,  327,  319,  326,  319,
      352,  330,  352,  335,  326,  352,  337,  352,  317,  331,
      315,  332,  326,  333,  322,  322,  315,  315,  317,  352,
      336,  319,  319,  315,  352,  317,  335,  322,  337,  322,
      322,  322,  322,  340,  319,  319,  352,  338,  336,  341,
      317,  315,  340,  336,  338,  338,  352,  341,  336,  352,

      352,  344,  352,  338,  322,  336,  340,  336,  319,  338,
      352,  341,  345,  317,  315,  342,  338,  352,  336,  343,
      334,  336,  345,  346,  344,  338,  338,  336,  338,  345,
      336,  346,  348,  339,  349,  345,  338,  350,  352,  350,
      345,  352,  339,  352,  352,  345,  346,  352,  352,  352,
      345,  345,  352,  352,  347,  348,  352,  349,  352,  345,
      350,  349,  351,  349,  352,  352,  349,  352,  349,   59,
       59,   59,   59,   59,   59,   63,   63,   63,   63,   63,
       63,   67,   67,   67,   67,   67,   67,   82,   82,  109,
      109,  109,  109,  109,  160,  352,  352,  160,  160,  160,

      161,  161,  161,  161,  161,  161,  169,  352,  169,  352,
      169,  169,  171,  352,  171,  171,  171,  171,  174,  352,
      174,  174,  174,  174,    9,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352

    } ;

static yyconst flex_int16_t yy_chk[1092] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    3,    3,    4,    4,
        5,    6,    5,    6,    5,    6,   22,   22,   25,   30,
      313,   32,  251,   31,   66,   66,   25,   30,   31,  172,
       36,   33,   74,   74,  159,   33,  162,  162,   81,   33,

       37,   30,   34,    3,   32,    4,   31,   50,   34,   80,
       30,   31,   36,   33,   35,   38,   32,   31,   33,   39,
       35,   30,   33,   37,   34,   45,   51,   36,   33,   50,
       45,   34,   37,  163,  163,   76,   35,   98,   38,   75,
       34,   84,   39,   35,   50,  171,  171,   72,   45,   51,
       69,   38,   35,   45,   65,   39,   43,   43,   51,   45,
       98,   57,   98,   84,   43,   43,   43,   43,   43,   43,
       43,   43,   43,   43,   43,   43,   43,   43,   43,   43,
       43,   43,   28,   84,   87,   43,   43,   43,   43,   43,
       43,   43,   43,   43,   43,   43,   43,   43,   43,   43,

       43,   43,   43,   43,   43,   44,   87,   46,   47,   83,
      173,  173,   47,   44,   46,   27,   47,   52,   26,   48,
       53,   24,   49,   52,   23,   48,   87,   44,   49,   46,
       47,   19,   83,  249,  249,   47,   44,   46,   83,   47,
       52,   48,   85,   53,   49,   47,   52,   44,   48,   46,
       86,   49,   18,   52,   93,   85,   53,   48,   16,   88,
       49,   55,   92,   14,   85,   55,   55,   55,   55,   55,
       55,   55,   88,   86,   55,   62,   62,   93,   85,   86,
       93,   88,   96,   55,   85,   92,   94,   55,   55,   95,
       55,   55,   55,   55,   55,   88,   94,   55,   92,   11,

       97,   88,   99,   55,   97,   96,   62,  105,  100,   94,
       62,  100,   95,  106,   96,   62,  103,   95,   62,   94,
       62,  104,   94,   97,  107,   99,  108,   97,    9,  105,
       99,  100,   97,    8,  100,  106,  100,  250,  250,  103,
      312,  312,    7,    0,  104,  105,    0,  107,  103,  108,
        0,  106,    0,  104,    0,    0,    0,    0,  112,  107,
      113,  108,  110,  110,  110,  110,  110,  110,  110,  110,
      110,  110,  110,  110,  110,  110,  110,  110,  110,  110,
      110,  112,  113,  114,    0,  115,  116,  112,  117,  119,
      118,  120,    0,    0,  122,  124,    0,  126,  127,  129,

      130,    0,  113,    0,    0,    0,  114,  115,    0,  116,
      117,  119,  114,  118,  120,  116,  131,  122,  124,  118,
      126,  127,  129,  130,  127,  120,  130,  115,  122,  124,
      117,  119,  132,  126,  133,  129,  134,  136,  135,  131,
        0,    0,    0,    0,  131,  143,  137,  138,    0,  141,
      142,  144,    0,    0,  145,  132,  148,  133,    0,  134,
      136,  135,  133,  135,  132,  136,  146,  143,  134,  137,
      138,  137,  141,  142,  144,  138,  145,  147,  144,  148,
      150,  141,  142,  143,  149,    0,    0,    0,  147,  146,
      155,  148,  145,  146,  151,    0,  157,  151,    0,  147,

        0,  153,  156,  150,  153,    0,  156,  149,  154,  150,
      175,  147,  157,  155,  176,  147,    0,  151,  157,  149,
      151,  154,  151,  153,  177,  156,  155,  153,    0,  156,
      154,  178,  175,  202,  156,  157,  176,  179,  157,  153,
      180,  181,    0,    0,  154,    0,  179,  177,  175,  182,
      154,  158,  176,  177,  178,  158,  202,  158,  158,  179,
      178,  158,  180,  181,  158,  158,  202,  158,  158,  179,
      183,  182,  184,  158,  184,  179,  185,  158,  180,  181,
      158,  158,  186,  187,  158,  188,    0,  158,  158,  182,
      158,  158,  183,  158,  184,  200,  184,  189,  185,  192,

      193,  194,  201,  189,  186,  203,  187,    0,  188,    0,
      183,  204,  184,    0,  185,  187,  205,  188,  200,  189,
      186,  206,  192,  193,  194,  201,  189,  208,  203,  200,
      192,  193,  194,  207,  204,  189,  201,  209,  203,  205,
        0,  210,  211,  206,  214,  204,  212,  213,  215,  208,
      205,  216,    0,  217,  219,  222,  207,    0,  218,  206,
      209,    0,  207,  210,  211,  208,  209,  214,  212,  213,
      220,  215,  224,  214,  216,  217,  219,  215,  222,  210,
      216,  218,  211,  229,  212,  230,  222,  213,  231,  234,
      218,  217,  219,  220,  232,  224,  233,    0,  235,    0,

        0,  237,  220,  224,    0,  236,  229,  238,  230,    0,
      236,  231,  234,    0,  240,  240,  232,  229,  233,  230,
      235,  231,  234,  242,  237,    0,  242,  236,    0,    0,
      238,  241,  232,  236,  233,  237,  235,  240,  240,  243,
      241,  238,  243,  236,  244,  245,  242,  255,  240,  242,
      246,  256,  244,  241,  257,    0,  245,  242,  265,    0,
        0,    0,  243,  241,  263,  243,  244,  245,  274,  241,
      255,    0,  246,  243,  256,  244,  255,  257,  264,  245,
      256,  265,  266,  257,  244,  245,  277,  263,  246,  248,
      274,  248,  275,  265,  263,  248,  248,  248,  248,  267,

      248,  264,  279,  287,  267,  266,  274,    0,  264,  277,
      284,  248,  288,  248,  275,  277,  285,  266,  248,  248,
      248,  248,  267,  248,  286,  279,  287,  267,  289,  248,
      275,  279,  284,  287,  267,  288,  290,  304,  285,  301,
        0,  302,  303,  310,  307,  309,  286,  288,  284,  306,
        0,  289,    0,  316,  285,    0,  318,    0,  289,  290,
      304,  301,  286,  302,  303,  310,  304,  307,  309,    0,
      317,  290,  306,  307,    0,  309,  316,  301,  318,  302,
      303,  310,  311,  328,  306,  311,    0,  319,  316,  329,
      311,  311,  330,  317,  320,  318,    0,  331,  320,    0,

        0,  335,    0,  334,  311,  317,  328,  334,  311,  319,
        0,  329,  336,  311,  311,  330,  320,    0,  328,  331,
      311,  320,  339,  340,  335,  334,  319,  330,  329,  335,
      334,  342,  344,  320,  345,  336,  331,  346,    0,  347,
      336,    0,  334,    0,    0,  339,  340,    0,    0,    0,
      339,  340,    0,    0,  342,  344,    0,  345,    0,  342,
      346,  344,  347,  345,    0,    0,  346,    0,  347,  353,
      353,  353,  353,  353,  353,  354,  354,  354,  354,  354,
      354,  355,  355,  355,  355,  355,  355,  356,  356,  357,
      357,  357,  357,  357,  358,    0,    0,  358,  358,  358,

      359,  359,  359,  359,  359,  359,  360,    0,  360,    0,
      360,  360,  361,    0,  361,  361,  361,  361,  362,    0,
      362,  362,  362,  362,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 1;

static yyconst flex_int16_t yy_rule_linenum[73] =
    {   0,
      118,  119,  120,  126,  127,  128,  129,  130,  131,  132,
      134,  143,  144,  145,  150,  151,  152,  153,  154,  155,
      156,  157,  158,  159,  160,  161,  162,  163,  164,  165,
      166,  167,  170,  180,  184,  188,  192,  196,  198,  211,
      213,  214,  215,  216,  217,  219,  221,  234,  238,  239,
      240,  241,  244,  245,  246,  247,  248,  249,  250,  251,
      252,  253,  254,  255,  256,  257,  258,  261,  266,  268,
      270,  274
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "cool.flex"
/*
%%
 *  The scanner definition for COOL.
 */
/*
 *  Stuff enclosed in %{ %} in the first section is copied verbatim to the
 *  output, so headers and global definitions are placed here to be visible
 * to the code in the file.  Don't remove anything that was here initially
 */
#line 12 "cool.flex"
#include <cool-parse.h>
#include <stringtab.h>
#include <utilities.h>
#include <math.h>
/* The compiler assumes these identifiers. */
#define yylval cool_yylval
#define yylex  cool_yylex

/* Max size of string constants */
#define MAX_STR_CONST 1025
#define YY_NO_UNPUT   /* keep g++ happy */

extern FILE *fin; /* we read from this file */

/* define YY_INPUT so we read from the FILE fin:
 * This change makes it possible to use this scanner in
 * the Cool compiler.
 */
#undef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( (result = fread( (char*)buf, sizeof(char), max_size, fin)) < 0) \
		YY_FATAL_ERROR( "read() in flex scanner failed");

char string_buf[MAX_STR_CONST]; /* to assemble string constants */
char *string_buf_ptr;

extern int curr_lineno;
extern int verbose_flag;

extern YYSTYPE cool_yylval;

/*
 *  Add Your own definitions here
 */




/*
 * Define names for regular expressions here.
 */
#line 966 "cool-lex.cc"

#define INITIAL 0
#define str 1
#define comment 2
#define line_comment 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
/* %if-c-only */
#include <unistd.h>
/* %endif */
/* %if-c++-only */
/* %endif */
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* %if-c-only Reentrant structure and macros (non-C++). */
/* %if-reentrant */
/* %if-c-only */

static int yy_init_globals (void );

/* %endif */
/* %if-reentrant */
/* %endif */
/* %endif End reentrant structures and macros. */

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* %if-bison-bridge */
/* %endif */

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

/* %not-for-header */

    static void yyunput (int c,char *buf_ptr  );
    
/* %ok-for-header */

/* %endif */

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT
/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif
/* %ok-for-header */

/* %endif */
#endif

/* %if-c-only */

/* %endif */

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* %if-c-only Standard (non-C++) definition */
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
/* %endif */
/* %if-c++-only C++ definition */
/* %endif */
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
/* %% [5.0] fread()/read() definition of YY_INPUT goes here unless we're doing C++ \ */\
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\
/* %if-c++-only C++ definition \ */\
/* %endif */

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
/* %if-c-only */
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
/* %endif */
/* %if-c++-only */
/* %endif */
#endif

/* %if-tables-serialization structures and prototypes */
/* %not-for-header */

/* %ok-for-header */

/* %not-for-header */

/* %tables-yydmap generated elements */
/* %endif */
/* end tables serialization structures and prototypes */

/* %ok-for-header */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1
/* %if-c-only Standard (non-C++) definition */

extern int yylex (void);

#define YY_DECL int yylex (void)
/* %endif */
/* %if-c++-only C++ definition */
/* %endif */
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

/* %% [6.0] YY_RULE_SETUP definition goes here */
#define YY_RULE_SETUP \
	YY_USER_ACTION

/* %not-for-header */

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
/* %% [7.0] user's declarations go here */
#line 113 "cool.flex"

 /*
  *  Nested comments
  */

#line 1222 "cool-lex.cc"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
/* %if-c-only */
			yyin = stdin;
/* %endif */
/* %if-c++-only */
/* %endif */

		if ( ! yyout )
/* %if-c-only */
			yyout = stdout;
/* %endif */
/* %if-c++-only */
/* %endif */

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
/* %% [8.0] yymore()-related code goes here */
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

/* %% [9.0] code to set up and find next match goes here */
		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 353 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1025 );

yy_find_action:
/* %% [10.0] code to find the action number goes here */
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

/* %% [11.0] code for yylineno update goes here */

do_action:	/* This label is used only to access EOF actions. */

/* %% [12.0] debug code goes here */
		if ( yy_flex_debug )
			{
			if ( yy_act == 0 )
				fprintf( stderr, "--scanner backing up\n" );
			else if ( yy_act < 73 )
				fprintf( stderr, "--accepting rule at line %ld (\"%s\")\n",
				         (long)yy_rule_linenum[yy_act], yytext );
			else if ( yy_act == 73 )
				fprintf( stderr, "--accepting default rule (\"%s\")\n",
				         yytext );
			else if ( yy_act == 74 )
				fprintf( stderr, "--(end of buffer or a NUL)\n" );
			else
				fprintf( stderr, "--EOF (start condition %d)\n", YY_START );
			}

		switch ( yy_act )
	{ /* beginning of action switch */
/* %% [13.0] actions go here */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 118 "cool.flex"
BEGIN(line_comment);
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 119 "cool.flex"
/* eat up anything thats not a newline */
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 120 "cool.flex"
{ curr_lineno++;
                          BEGIN(INITIAL);
                        }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 126 "cool.flex"
BEGIN(comment);
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 127 "cool.flex"
/* eat anything that's not a '*' */
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 128 "cool.flex"
/* eat up new open comment */
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 129 "cool.flex"
/* eat up '*'s not followed by ')'s */
	YY_BREAK
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 130 "cool.flex"
curr_lineno++;    
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 131 "cool.flex"
BEGIN(INITIAL);
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 132 "cool.flex"

	YY_BREAK
case 11:
YY_RULE_SETUP
#line 134 "cool.flex"
{ cool_yylval.error_msg = "Unmatched *)";
                          return (ERROR);
                        }
	YY_BREAK
/*
  *  The multiple-character operators.
  */
case 12:
YY_RULE_SETUP
#line 143 "cool.flex"
{ return (DARROW); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 144 "cool.flex"
{ return (ASSIGN); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 145 "cool.flex"
{ return (LE); }
	YY_BREAK
/*
  * Keywords are case-insensitive except for the values true and false,
  * which must begin with a lower-case letter.
  */
case 15:
YY_RULE_SETUP
#line 150 "cool.flex"
{ return (CLASS); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 151 "cool.flex"
{ return (ELSE); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 152 "cool.flex"
{ return (FI); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 153 "cool.flex"
{ return (IF); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 154 "cool.flex"
{ return (IN); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 155 "cool.flex"
{ return (INHERITS); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 156 "cool.flex"
{ return (LET); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 157 "cool.flex"
{ return (LOOP); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 158 "cool.flex"
{ return (POOL); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 159 "cool.flex"
{ return (THEN); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 160 "cool.flex"
{ return (WHILE); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 161 "cool.flex"
{ return (CASE); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 162 "cool.flex"
{ return (ESAC); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 163 "cool.flex"
{ return (OF); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 164 "cool.flex"
{ return (NEW); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 165 "cool.flex"
{ return (ISVOID); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 166 "cool.flex"
{ return (NOT); } 
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 167 "cool.flex"
{ cool_yylval.boolean = true;
                  return (BOOL_CONST);
                }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 170 "cool.flex"
{ cool_yylval.boolean = false;
                  return (BOOL_CONST);
                }
	YY_BREAK
/*
  *  String constants (C syntax)
  *  Escape sequence \c is accepted for all characters c. Except for 
  *  \n \t \b \f, the result is c.
  *
  */
case 34:
YY_RULE_SETUP
#line 180 "cool.flex"
{ cool_yylval.symbol = inttable.add_string(yytext);
                  return (TYPEID);
                }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 184 "cool.flex"
{ cool_yylval.symbol = inttable.add_string(yytext);
                  return (OBJECTID);
                }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 188 "cool.flex"
{ string_buf_ptr = string_buf;
                  BEGIN(str);
                }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 192 "cool.flex"
{ BEGIN(INITIAL);
                  *string_buf_ptr = '\0';
                }
	YY_BREAK
case 38:
/* rule 38 can match eol */
YY_RULE_SETUP
#line 196 "cool.flex"
{ return (ERROR); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 198 "cool.flex"
{
                    int result;
     
                    (void) sscanf( yytext + 1, "%o", &result );
                           
                    if ( result > 0xff ) {
                        cool_yylval.error_msg = "Unescaped chars";
                        return (ERROR);
                    }
                    
                    *string_buf_ptr++ = result;
                  }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 211 "cool.flex"
{ return (ERROR); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 213 "cool.flex"
*string_buf_ptr++ = '\n';
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 214 "cool.flex"
*string_buf_ptr++ = '\t';
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 215 "cool.flex"
*string_buf_ptr++ = '\r';
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 216 "cool.flex"
*string_buf_ptr++ = '\b';
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 217 "cool.flex"
*string_buf_ptr++ = '\f';
	YY_BREAK
case 46:
/* rule 46 can match eol */
YY_RULE_SETUP
#line 219 "cool.flex"
*string_buf_ptr++ = yytext[1];
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 221 "cool.flex"
{
                   char *yptr = yytext;
                         
                   while ( *yptr ) {
                           *string_buf_ptr++ = *yptr++;
                   }
                   
                   cool_yylval.symbol = inttable.add_string(yytext); 
                   return (STR_CONST);
                }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 234 "cool.flex"
{ cool_yylval.symbol = inttable.add_string(yytext); 
                  return (INT_CONST); 
                }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 238 "cool.flex"
{ return(43); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 239 "cool.flex"
{ return(45); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 240 "cool.flex"
{ return(42); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 241 "cool.flex"
{ return(47); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 244 "cool.flex"
{ return(59); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 245 "cool.flex"
{ return(40); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 246 "cool.flex"
{ return(41); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 247 "cool.flex"
{ return(123);}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 248 "cool.flex"
{ return(125);}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 249 "cool.flex"
{ return(91); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 250 "cool.flex"
{ return(93); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 251 "cool.flex"
{ return(58); }         
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 252 "cool.flex"
{ return(46); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 253 "cool.flex"
{ return(62); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 254 "cool.flex"
{ return(60); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 255 "cool.flex"
{ return(44); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 256 "cool.flex"
{ return(126);}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 257 "cool.flex"
{ return(64); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 258 "cool.flex"
{ return(61); }
	YY_BREAK
case 68:
/* rule 68 can match eol */
YY_RULE_SETUP
#line 261 "cool.flex"
{ cool_yylval.error_msg = "_";
                       return(ERROR);
                     }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 266 "cool.flex"

	YY_BREAK
case 70:
/* rule 70 can match eol */
YY_RULE_SETUP
#line 268 "cool.flex"
{ curr_lineno++; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 270 "cool.flex"
{ cool_yylval.error_msg = "Null char present.";
                  return(ERROR);
                }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 274 "cool.flex"
{ cool_yylval.error_msg = yytext;
                  return(ERROR);
                }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 277 "cool.flex"
ECHO;
	YY_BREAK
#line 1764 "cool-lex.cc"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(str):
case YY_STATE_EOF(comment):
case YY_STATE_EOF(line_comment):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
/* %% [14.0] code to do back-up for compressed tables and set up yy_cp goes here */
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */
/* %ok-for-header */

/* %if-c++-only */
/* %not-for-header */

/* %ok-for-header */

/* %endif */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
/* %if-c-only */
static int yy_get_next_buffer (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

/* %if-c-only */
/* %not-for-header */

    static yy_state_type yy_get_previous_state (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
/* %% [15.0] code to get the start state into yy_current_state goes here */
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
/* %% [16.0] code to find the next state goes here */
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 66);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 353 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
/* %if-c-only */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
/* %endif */
/* %if-c++-only */
/* %endif */
{
	register int yy_is_jam;
    /* %% [17.0] code to find the next state, and perhaps do backing up, goes here */
	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 66;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 353 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 352);

	return yy_is_jam ? 0 : yy_current_state;
}

/* %if-c-only */

    static void yyunput (int c, register char * yy_bp )
/* %endif */
/* %if-c++-only */
/* %endif */
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

/* %% [18.0] update yylineno here */

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}
/* %if-c-only */

/* %endif */

/* %if-c-only */
#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

/* %endif */
/* %if-c++-only */
/* %endif */
{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

/* %% [19.0] update BOL and yylineno */

	return c;
}
/* %if-c-only */
#endif	/* ifndef YY_NO_INPUT */
/* %endif */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
/* %if-c-only */
    void yyrestart  (FILE * input_file )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
/* %if-c-only */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

/* %if-c-only */
static void yy_load_buffer_state  (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
/* %if-c-only */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
/* %endif */
/* %if-c++-only */
/* %endif */
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
/* %if-c-only */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* %if-c-only */

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* %endif */

/* %if-c++-only */
/* %endif */

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
/* %if-c-only */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )
/* %endif */
/* %if-c++-only */
/* %endif */

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

/* %if-c-only */

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
/* %endif */
/* %if-c++-only */
/* %endif */
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
/* %if-c-only */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/* %if-c-or-c++ */
/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
/* %if-c-only */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}
/* %endif */

/* %if-c-or-c++ */
/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
/* %if-c-only */
void yypop_buffer_state (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}
/* %endif */

/* %if-c-or-c++ */
/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
/* %if-c-only */
static void yyensure_buffer_stack (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}
/* %endif */

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

/* %if-c-only */
static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}
/* %endif */
/* %if-c++-only */
/* %endif */

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/* %if-c-only */
/* %if-reentrant */
/* %endif */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/* %if-reentrant */
/* %endif */

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

/* %endif */

/* %if-reentrant */
/* %if-bison-bridge */
/* %endif */
/* %endif if-c-only */

/* %if-c-only */
static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}
/* %endif */

/* %if-c-only SNIP! this currently causes conflicts with the c++ scanner */
/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

/* %if-reentrant */
/* %endif */
    return 0;
}
/* %endif */

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

/* %if-tables-serialization definitions */
/* %define-yytables   The name for this specific scanner's tables. */
#define YYTABLES_NAME "yytables"
/* %endif */

/* %ok-for-header */

#line 277 "cool.flex"
