#line 2 "cool-lex.cc"

#line 4 "cool-lex.cc"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

/* %not-for-header */

/* %if-c-only */
/* %if-not-reentrant */

/* %endif */
/* %endif */
/* %ok-for-header */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* %if-c++-only */
/* %endif */

/* %if-c-only */
    
/* %endif */

/* %if-c-only */

/* %endif */

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
/* %if-c-only */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>
/* %endif */

/* %if-tables-serialization */
/* %endif */
/* end standard C headers. */

/* %if-c-or-c++ */
/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* %endif */

/* %if-c++-only */
/* %endif */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* %not-for-header */

/* Returned upon end-of-file. */
#define YY_NULL 0
/* %ok-for-header */

/* %not-for-header */

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)
/* %ok-for-header */

/* %if-reentrant */
/* %endif */

/* %if-not-reentrant */

/* %endif */

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

/* %if-not-reentrant */
extern int yyleng;
/* %endif */

/* %if-c-only */
/* %if-not-reentrant */
extern FILE *yyin, *yyout;
/* %endif */
/* %endif */

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
/* %if-c-only */
	FILE *yy_input_file;
/* %endif */

/* %if-c++-only */
/* %endif */

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */

/* %if-not-reentrant */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */
/* %endif */
/* %ok-for-header */

/* %endif */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* %if-c-only Standard (non-C++) definition */

/* %if-not-reentrant */
/* %not-for-header */

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;
/* %ok-for-header */

/* %endif */

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

/* %endif */

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* %% [1.0] yytext/yyin/yyout/yy_state_type/yylineno etc. def's & init go here */

#define FLEX_DEBUG

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

/* %if-c-only Standard (non-C++) definition */

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* %endif */

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
/* %% [2.0] code to fiddle yytext and yyleng for yymore() goes here \ */\
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
/* %% [3.0] code to copy yytext_ptr to yytext[] goes here, if %array \ */\
	(yy_c_buf_p) = yy_cp;

/* %% [4.0] data tables for the DFA and the user's section 1 definitions go here */
#define YY_NUM_RULES 67
#define YY_END_OF_BUFFER 68
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[290] =
    {   0,
        0,    0,    0,    0,    5,    5,    2,    2,   68,   65,
       63,   64,   35,   53,   54,   50,   48,   49,   60,   51,
       47,   59,   52,   62,   65,   61,   65,   65,   65,   65,
       65,   65,   65,   65,   65,   65,   65,   57,   58,   65,
       65,   65,   65,   65,   65,   65,   65,   65,   65,   65,
       55,   65,   56,   65,   46,   37,   36,   67,    5,    8,
        5,    7,    2,    3,   63,    4,   11,    1,   47,   59,
       52,   13,   62,   12,   61,   33,   33,   33,    0,   33,
       33,    0,   16,   16,   17,   18,   33,   17,   33,   33,
        0,   33,   33,    0,   27,   27,   33,    0,   33,    0,

       33,    0,   34,   34,   34,   34,   34,   34,   16,   16,
       17,   18,   34,   34,   34,   34,   34,   27,   34,   34,
       34,    0,   34,    0,    0,   17,    0,    0,   18,    0,
        0,   16,   46,   45,   38,   39,   43,   44,   40,   42,
       41,    5,    6,    7,    9,    7,    2,   33,    0,   33,
        0,    0,   33,    0,   33,    0,    0,   33,    0,   33,
        0,    0,   20,   20,   33,    0,   20,   28,   28,   30,
       30,   28,   33,    0,   33,    0,   33,    0,   34,   34,
       34,   34,   34,    0,   34,   34,   20,   34,   28,   30,
       34,   34,   34,    0,    0,   34,   20,    0,    0,    0,

       30,    0,    0,    0,   20,   20,   38,   39,    0,    9,
       25,   25,   33,    0,   25,   15,   15,   26,   26,   15,
       33,    0,   33,    0,    0,   21,   21,   22,   22,   23,
       23,   33,    0,   25,   34,   15,   26,   34,    0,   34,
       34,   21,   22,   23,   31,   31,   23,   34,   23,   15,
       21,   26,   26,   15,   15,   22,   15,   38,   10,   14,
       14,   33,    0,   33,    0,    0,   24,   24,   14,   32,
       32,   34,   34,   24,   14,   33,    0,   29,   29,   29,
       34,   29,   33,    0,   34,   19,   19,   19,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    1,    1,    1,    1,    1,    5,
        6,    7,    8,    1,    9,   10,   11,   12,   12,   12,
       12,   12,   12,   12,   12,   13,   13,   14,   15,   16,
       17,   18,    1,    1,   19,   20,   21,   22,   23,   24,
       20,   25,   26,   20,   20,   27,   20,   28,   29,   30,
       20,   31,   32,   33,   34,   35,   36,   20,   20,   20,
       37,   38,   39,    1,   40,    1,   41,   42,   43,   44,

       45,   46,   47,   48,   49,   47,   47,   50,   47,   51,
       52,   53,   47,   54,   55,   56,   57,   58,   59,   47,
       47,   47,   60,   61,   62,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[64] =
    {   0,
        1,    1,    2,    3,    1,    1,    4,    1,    1,    1,
        1,    5,    5,    1,    1,    1,    1,    1,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    1,    3,    1,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    1,
        1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[300] =
    {   0,
        0,    0,   61,   63,   65,   66,  303,  301,  300,  810,
      274,  810,  810,  258,  810,  256,  810,  243,  810,  810,
       62,  236,  183,   67,  171,  165,    0,   59,   52,   54,
       66,   81,   85,   73,   64,   57,   63,  810,  810,    0,
      104,  108,  103,  115,  126,  127,  114,  107,  142,  132,
      810,  185,  810,  810,    0,  810,  810,  173,    0,  810,
      174,   85,    0,  810,  160,  810,  810,  810,   83,  139,
      136,  810,  125,  810,  114,    0,  145,   87,  206,  167,
      182,  213,    0,  810,    0,  157,  181,  223,  141,  192,
      226,  205,  216,  224,    0,  810,  227,  234,  228,  246,

      244,  249,    0,  258,  273,  262,  277,  270,    0,  272,
        0,  159,  266,  269,  274,  280,  276,    0,  292,  305,
      295,  313,  314,  310,  321,  810,  323,  332,  330,  350,
      357,  400,    0,  810,  179,  182,  810,  810,  810,  810,
      810,    0,  810,  305,   82,  353,    0,  344,  363,  349,
      367,  389,  386,  393,  396,  399,  430,  417,  420,  333,
      385,  440,    0,  810,  434,  436,  437,    0,  810,    0,
      810,  810,  443,  444,  448,  449,  452,  453,  451,  456,
      461,  465,  475,  483,  495,  487,    0,  489,    0,    0,
      493,  496,  500,  504,  518,  501,  810,  525,  532,  541,

      551,  537,  552,  547,  810,  593,  383,  388,   81,  810,
        0,  810,  527,  535,  542,    0,  810,    0,  810,  810,
      574,  578,  511,  557,  598,    0,  810,    0,  810,    0,
      810,  588,  592,    0,  595,    0,    0,  596,  617,  611,
      625,    0,    0,    0,    0,  810,  810,  632,  635,  628,
      810,  638,  629,  810,  637,  640,  671,  470,   78,    0,
      810,  643,  656,  651,  666,  685,    0,  810,    0,    0,
      810,  674,  684,    0,  687,  681,  682,    0,  810,  688,
      691,    0,  698,  701,  708,    0,  810,    0,  810,  769,
      774,  779,   76,   72,  784,  789,  794,  799,  804

    } ;

static yyconst flex_int16_t yy_def[300] =
    {   0,
      289,    1,  290,  290,  291,  291,  292,  292,  289,  289,
      289,  289,  289,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  289,  289,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,
      289,  289,  289,  289,  295,  289,  289,  296,  297,  289,
      297,  298,  299,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  293,  293,  293,  289,  293,
      293,  289,  293,  289,  293,  293,  293,  289,  293,  293,
      289,  293,  293,  289,  293,  289,  293,  289,  293,  289,

      293,  289,  294,  294,  294,  294,  294,  294,  294,  289,
      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  289,  294,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  295,  289,  289,  289,  289,  289,  289,  289,
      289,  297,  289,  298,  289,  298,  299,  293,  289,  293,
      289,  289,  293,  289,  293,  289,  289,  293,  289,  293,
      289,  289,  293,  289,  293,  289,  289,  293,  289,  293,
      289,  289,  293,  289,  293,  289,  293,  289,  294,  294,
      294,  294,  294,  289,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  289,  289,  294,  289,  289,  289,  289,

      289,  289,  289,  289,  289,  289,  289,  289,  289,  289,
      293,  289,  293,  289,  289,  293,  289,  293,  289,  289,
      293,  289,  293,  289,  289,  293,  289,  293,  289,  293,
      289,  293,  289,  294,  294,  294,  294,  294,  289,  294,
      294,  294,  294,  294,  294,  289,  289,  294,  289,  289,
      289,  289,  289,  289,  289,  289,  289,  289,  289,  293,
      289,  293,  289,  293,  289,  289,  293,  289,  294,  294,
      289,  294,  294,  294,  289,  293,  289,  293,  289,  289,
      294,  294,  293,  289,  294,  293,  289,  294,    0,  289,
      289,  289,  289,  289,  289,  289,  289,  289,  289

    } ;

static yyconst flex_int16_t yy_nxt[874] =
    {   0,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       20,   21,   21,   22,   23,   24,   25,   26,   27,   27,
       28,   27,   29,   30,   27,   31,   32,   33,   34,   35,
       27,   27,   36,   27,   27,   37,   38,   10,   39,   10,
       40,   40,   41,   40,   42,   43,   40,   40,   44,   45,
       46,   47,   48,   40,   40,   49,   40,   40,   50,   51,
       52,   53,   54,   56,   57,   56,   57,   60,   60,   61,
       61,   62,   62,   69,   69,   72,  103,   77,   80,   83,
       76,   99,   73,   81,  209,   78,  259,  101,  209,   85,
      145,  146,   97,   86,   69,   69,   95,   87,   58,   77,

       58,   80,   83,   89,   99,  150,   81,   92,   78,   90,
      101,   85,   82,   93,   84,   97,   86,  100,   95,   79,
       87,  108,  104,  102,   98,   89,   88,  150,  109,   92,
      105,   75,   90,   96,  106,  119,   93,  118,  111,  107,
       73,   91,  112,  108,  104,   94,  113,  151,  114,  116,
       71,  109,   70,  105,  115,  117,  123,  106,  119,  118,
      111,   65,  107,  110,   79,  112,  120,   98,   82,  113,
      114,  116,  121,  163,   96,   88,  148,  115,  117,  123,
      143,  158,   75,  185,  135,  136,   91,   94,   74,  120,
      207,  208,  102,  208,  208,  121,  163,   71,  153,  148,

      155,  164,  122,  124,  158,  149,  185,  125,  126,  127,
       84,  128,  129,  130,  137,  160,  131,  159,  138,  159,
      165,  153,  155,  139,  151,  124,  140,  154,  141,  125,
      126,  156,  127,   84,  128,  129,  130,  149,  160,  131,
      168,  161,  156,  165,  154,  132,  151,  159,  170,   70,
      175,   68,  166,  156,  166,  173,  171,  161,  164,  169,
      149,   67,  174,  168,   66,  169,  152,  154,  176,  177,
      159,  170,  175,  157,  178,   65,  171,  166,  173,  171,
      161,  164,  169,  162,  172,  174,  167,  174,  176,  179,
      176,  180,  177,  181,  174,  182,  183,  178,  184,  289,

      186,  187,  188,   64,  178,   64,  176,  289,  190,  178,
      289,  289,  179,  180,  289,  189,  181,  182,  149,  183,
      191,  184,  154,  186,  187,  188,  161,  192,  193,  164,
      184,  190,  184,  151,  166,  176,  171,  156,  189,  196,
      169,  149,  289,  191,  289,  176,  194,  289,  178,  192,
      151,  193,  174,  164,  159,  194,  169,  176,  210,  146,
      289,  223,  196,  154,  149,  176,  211,  176,  289,  194,
      149,  178,  151,  195,  178,  156,  164,  159,  200,  169,
      213,  197,  171,  198,  223,  212,  154,  289,  211,  289,
      159,  161,  199,  224,  258,  208,  289,  156,  214,  208,

      208,  200,  289,  213,  212,  171,  289,  212,  216,  214,
      201,  212,  289,  224,  161,  217,  218,  202,  203,  219,
      214,  214,  176,  212,  159,  178,  289,  214,  200,  289,
      216,  204,  205,  212,  161,  169,  224,  217,  218,  221,
      203,  219,  222,  214,  176,  224,  217,  159,  178,  215,
      219,  200,  217,  217,  204,  205,  219,  161,  169,  219,
      206,  221,  222,  226,  222,  227,  227,  289,  224,  228,
      229,  289,  219,  234,  217,  230,  231,  222,  232,  233,
      222,  208,  208,  236,  222,  237,  226,  235,  227,  227,
      220,  224,  228,  229,  227,  234,  227,  227,  230,  231,

      225,  232,  233,  229,  229,  236,  238,  237,  231,  231,
      235,  212,  233,  233,  239,  241,  214,  240,  242,  243,
      289,  217,  245,  244,  289,  219,  246,  248,  289,  238,
      289,  289,  289,  289,  289,  239,  264,  239,  241,  240,
      246,  242,  243,  239,  245,  231,  244,  224,  246,  227,
      248,  233,  231,  229,  217,  222,  231,  219,  260,  264,
      246,  233,  246,  214,  246,  224,  261,  229,  231,  254,
      227,  265,  219,  261,  233,  231,  217,  229,  247,  219,
      227,  260,  265,  214,  289,  249,  214,  261,  224,  261,
      229,  254,  250,  227,  219,  261,  261,  252,  289,  289,

      229,  251,  261,  227,  262,  265,  214,  254,  263,  289,
      267,  251,  253,  219,  268,  255,  289,  265,  270,  256,
      231,  224,  227,  265,  214,  289,  269,  262,  263,  289,
      289,  263,  267,  289,  263,  219,  268,  255,  263,  271,
      270,  272,  256,  231,  224,  227,  265,  214,  268,  269,
      273,  263,  268,  257,  274,  261,  271,  268,  266,  261,
      261,  271,  268,  265,  272,  289,  289,  263,  276,  289,
      289,  263,  278,  273,  289,  289,  274,  271,  289,  268,
      289,  277,  261,  261,  268,  265,  265,  279,  261,  261,
      263,  276,  268,  268,  278,  268,  265,  263,  265,  281,

      268,  263,  261,  277,  277,  282,  279,  289,  279,  279,
      277,  279,  277,  283,  284,  268,  277,  289,  289,  265,
      284,  289,  281,  285,  263,  261,  279,  282,  279,  286,
      279,  275,  287,  277,  277,  277,  283,  284,  289,  288,
      289,  284,  284,  284,  279,  280,  285,  280,  284,  289,
      289,  284,  286,  289,  289,  287,  289,  289,  287,  289,
      289,  287,  288,  289,  289,  289,  289,  289,  287,   55,
       55,   55,   55,   55,   59,   59,   59,   59,   59,   63,
       63,   63,   63,   63,  133,  289,  289,  133,  133,  134,
      134,  134,  134,  134,  142,  289,  142,  289,  142,  144,

      289,  144,  144,  144,  147,  289,  147,  147,  147,    9,
      289,  289,  289,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  289
    } ;

static yyconst flex_int16_t yy_chk[874] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    3,    3,    4,    4,    5,    6,    5,
        6,    5,    6,   21,   21,   24,  294,   28,   29,   30,
      293,   36,   24,   29,  259,   28,  209,   37,  145,   31,
       62,   62,   35,   31,   69,   69,   34,   31,    3,   28,

        4,   29,   30,   32,   36,   78,   29,   33,   28,   32,
       37,   31,   29,   33,   30,   35,   31,   36,   34,   28,
       31,   43,   41,   37,   35,   32,   31,   78,   43,   33,
       41,   75,   32,   34,   42,   48,   33,   47,   44,   42,
       73,   32,   44,   43,   41,   33,   44,   78,   45,   46,
       71,   43,   70,   41,   45,   46,   50,   42,   48,   47,
       44,   65,   42,   43,   41,   44,   49,   48,   42,   44,
       45,   46,   49,   89,   47,   44,   77,   45,   46,   50,
       61,   86,   26,  112,   58,   58,   45,   46,   25,   49,
      135,  135,   50,  136,  136,   49,   89,   23,   80,   77,

       81,   89,   49,   52,   86,   77,  112,   52,   52,   52,
       52,   52,   52,   52,   58,   87,   52,   86,   58,  112,
       90,   80,   81,   58,   79,   52,   58,   80,   58,   52,
       52,   82,   52,   52,   52,   52,   52,   79,   87,   52,
       92,   87,   81,   90,   82,   52,   79,   88,   93,   22,
       99,   18,   90,   82,   91,   97,   94,   88,   91,   94,
       79,   16,   98,   92,   14,   92,   79,   82,  100,  101,
       88,   93,   99,   82,  102,   11,   93,   91,   97,   94,
       88,   91,   94,   88,   94,   98,   91,   97,   99,  104,
      100,  105,  101,  106,   98,  107,  108,  102,  110,    9,

      113,  114,  115,    8,  101,    7,  100,    0,  117,  102,
      144,  144,  104,  105,    0,  116,  106,  107,  104,  108,
      119,  110,  106,  113,  114,  115,  113,  120,  121,  114,
      108,  117,  110,  105,  115,  122,  117,  107,  116,  123,
      116,  124,    0,  119,    0,  127,  122,    0,  127,  120,
      128,  121,  119,  125,  129,  121,  125,  122,  146,  146,
        0,  160,  123,  128,  124,  120,  148,  127,    0,  122,
      124,  127,  128,  122,  123,  131,  125,  129,  130,  125,
      150,  125,  130,  127,  160,  149,  128,    0,  148,    0,
      129,  131,  128,  160,  207,  207,    0,  131,  151,  208,

      208,  130,    0,  150,  148,  130,    0,  149,  153,  150,
      130,  152,    0,  161,  131,  154,  155,  131,  132,  156,
      152,  151,  132,  149,  132,  132,    0,  151,  132,    0,
      153,  132,  132,  152,  132,  132,  161,  154,  155,  158,
      132,  156,  159,  152,  132,  161,  153,  132,  132,  152,
      157,  132,  157,  154,  132,  132,  155,  132,  132,  156,
      132,  158,  162,  165,  159,  166,  167,    0,  162,  173,
      174,    0,  157,  179,  157,  175,  176,  158,  177,  178,
      159,  258,  258,  181,  162,  182,  165,  180,  166,  167,
      157,  162,  173,  174,  165,  179,  166,  167,  175,  176,

      162,  177,  178,  173,  174,  181,  183,  182,  175,  176,
      180,  179,  177,  178,  184,  186,  180,  185,  188,  191,
        0,  181,  193,  192,    0,  182,  194,  196,    0,  183,
        0,    0,    0,    0,    0,  183,  223,  184,  186,  185,
      195,  188,  191,  184,  193,  195,  192,  186,  194,  188,
      196,  198,  198,  191,  199,  185,  192,  202,  213,  223,
      193,  196,  195,  199,  194,  202,  214,  200,  195,  204,
      200,  223,  203,  215,  198,  198,  199,  201,  195,  202,
      201,  213,  224,  203,    0,  198,  199,  213,  202,  214,
      200,  204,  199,  200,  203,  214,  215,  202,    0,    0,

      201,  200,  215,  201,  221,  224,  203,  204,  222,    0,
      232,  201,  203,  206,  233,  206,    0,  224,  238,  206,
      206,  206,  206,  225,  206,    0,  235,  221,  225,    0,
        0,  222,  232,    0,  221,  206,  233,  206,  222,  239,
      238,  240,  206,  206,  206,  206,  225,  206,  232,  235,
      241,  225,  233,  206,  248,  235,  238,  249,  225,  250,
      253,  239,  256,  252,  240,    0,    0,  255,  262,    0,
        0,  240,  264,  241,    0,    0,  248,  239,    0,  249,
        0,  263,  250,  253,  256,  241,  252,  265,  250,  253,
      255,  262,  248,  257,  264,  249,  257,  255,  252,  272,

      256,  257,  257,  262,  263,  273,  266,    0,  275,  265,
      266,  264,  275,  276,  277,  257,  263,    0,    0,  257,
      280,    0,  272,  281,  257,  257,  265,  273,  266,  283,
      275,  257,  284,  266,  272,  275,  276,  277,    0,  285,
        0,  276,  277,  280,  273,  266,  281,  275,  280,    0,
        0,  281,  283,    0,    0,  284,    0,    0,  283,    0,
        0,  284,  285,    0,    0,    0,    0,    0,  285,  290,
      290,  290,  290,  290,  291,  291,  291,  291,  291,  292,
      292,  292,  292,  292,  295,    0,    0,  295,  295,  296,
      296,  296,  296,  296,  297,    0,  297,    0,  297,  298,

        0,  298,  298,  298,  299,    0,  299,  299,  299,  289,
      289,  289,  289,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  289
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 1;

static yyconst flex_int16_t yy_rule_linenum[67] =
    {   0,
      109,  110,  111,  117,  118,  119,  120,  121,  122,  123,
      125,  134,  135,  141,  142,  143,  144,  145,  146,  147,
      148,  149,  150,  151,  152,  153,  154,  155,  156,  157,
      158,  161,  171,  175,  179,  183,  187,  189,  202,  204,
      205,  206,  207,  208,  210,  212,  225,  229,  230,  231,
      232,  235,  236,  237,  238,  239,  240,  241,  242,  243,
      244,  245,  247,  248,  249,  250
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "cool.flex"
/*
%%
 *  The scanner definition for COOL.
 */
/*
 *  Stuff enclosed in %{ %} in the first section is copied verbatim to the
 *  output, so headers and global definitions are placed here to be visible
 * to the code in the file.  Don't remove anything that was here initially
 */
#line 12 "cool.flex"
#include <cool-parse.h>
#include <stringtab.h>
#include <utilities.h>
#include <math.h>
/* The compiler assumes these identifiers. */
#define yylval cool_yylval
#define yylex  cool_yylex

/* Max size of string constants */
#define MAX_STR_CONST 1025
#define YY_NO_UNPUT   /* keep g++ happy */

extern FILE *fin; /* we read from this file */

/* define YY_INPUT so we read from the FILE fin:
 * This change makes it possible to use this scanner in
 * the Cool compiler.
 */
#undef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( (result = fread( (char*)buf, sizeof(char), max_size, fin)) < 0) \
		YY_FATAL_ERROR( "read() in flex scanner failed");

char string_buf[MAX_STR_CONST]; /* to assemble string constants */
char *string_buf_ptr;

extern int curr_lineno;
extern int verbose_flag;

extern YYSTYPE cool_yylval;

/*
 *  Add Your own definitions here
 */




/*
 * Define names for regular expressions here.
 */
#line 893 "cool-lex.cc"

#define INITIAL 0
#define str 1
#define comment 2
#define line_comment 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
/* %if-c-only */
#include <unistd.h>
/* %endif */
/* %if-c++-only */
/* %endif */
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* %if-c-only Reentrant structure and macros (non-C++). */
/* %if-reentrant */
/* %if-c-only */

static int yy_init_globals (void );

/* %endif */
/* %if-reentrant */
/* %endif */
/* %endif End reentrant structures and macros. */

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* %if-bison-bridge */
/* %endif */

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

/* %not-for-header */

    static void yyunput (int c,char *buf_ptr  );
    
/* %ok-for-header */

/* %endif */

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT
/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif
/* %ok-for-header */

/* %endif */
#endif

/* %if-c-only */

/* %endif */

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* %if-c-only Standard (non-C++) definition */
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
/* %endif */
/* %if-c++-only C++ definition */
/* %endif */
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
/* %% [5.0] fread()/read() definition of YY_INPUT goes here unless we're doing C++ \ */\
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\
/* %if-c++-only C++ definition \ */\
/* %endif */

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
/* %if-c-only */
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
/* %endif */
/* %if-c++-only */
/* %endif */
#endif

/* %if-tables-serialization structures and prototypes */
/* %not-for-header */

/* %ok-for-header */

/* %not-for-header */

/* %tables-yydmap generated elements */
/* %endif */
/* end tables serialization structures and prototypes */

/* %ok-for-header */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1
/* %if-c-only Standard (non-C++) definition */

extern int yylex (void);

#define YY_DECL int yylex (void)
/* %endif */
/* %if-c++-only C++ definition */
/* %endif */
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

/* %% [6.0] YY_RULE_SETUP definition goes here */
#define YY_RULE_SETUP \
	YY_USER_ACTION

/* %not-for-header */

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
/* %% [7.0] user's declarations go here */
#line 104 "cool.flex"

 /*
  *  Nested comments
  */

#line 1149 "cool-lex.cc"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
/* %if-c-only */
			yyin = stdin;
/* %endif */
/* %if-c++-only */
/* %endif */

		if ( ! yyout )
/* %if-c-only */
			yyout = stdout;
/* %endif */
/* %if-c++-only */
/* %endif */

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
/* %% [8.0] yymore()-related code goes here */
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

/* %% [9.0] code to set up and find next match goes here */
		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 290 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 810 );

yy_find_action:
/* %% [10.0] code to find the action number goes here */
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

/* %% [11.0] code for yylineno update goes here */

do_action:	/* This label is used only to access EOF actions. */

/* %% [12.0] debug code goes here */
		if ( yy_flex_debug )
			{
			if ( yy_act == 0 )
				fprintf( stderr, "--scanner backing up\n" );
			else if ( yy_act < 67 )
				fprintf( stderr, "--accepting rule at line %ld (\"%s\")\n",
				         (long)yy_rule_linenum[yy_act], yytext );
			else if ( yy_act == 67 )
				fprintf( stderr, "--accepting default rule (\"%s\")\n",
				         yytext );
			else if ( yy_act == 68 )
				fprintf( stderr, "--(end of buffer or a NUL)\n" );
			else
				fprintf( stderr, "--EOF (start condition %d)\n", YY_START );
			}

		switch ( yy_act )
	{ /* beginning of action switch */
/* %% [13.0] actions go here */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 109 "cool.flex"
BEGIN(line_comment);
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 110 "cool.flex"
/* eat up anything thats not a newline */
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 111 "cool.flex"
{ curr_lineno++;
                          BEGIN(INITIAL);
                        }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 117 "cool.flex"
BEGIN(comment);
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 118 "cool.flex"
/* eat anything that's not a '*' */
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 119 "cool.flex"
/* eat up new open comment */
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 120 "cool.flex"
/* eat up '*'s not followed by ')'s */
	YY_BREAK
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 121 "cool.flex"
curr_lineno++;    
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 122 "cool.flex"
BEGIN(INITIAL);
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 123 "cool.flex"

	YY_BREAK
case 11:
YY_RULE_SETUP
#line 125 "cool.flex"
{ cool_yylval.error_msg = "Unmatched *)";
                          return (ERROR);
                        }
	YY_BREAK
/*
  *  The multiple-character operators.
  */
case 12:
YY_RULE_SETUP
#line 134 "cool.flex"
{ return (DARROW); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 135 "cool.flex"
{ return (ASSIGN); }
	YY_BREAK
/*
  * Keywords are case-insensitive except for the values true and false,
  * which must begin with a lower-case letter.
  */
case 14:
YY_RULE_SETUP
#line 141 "cool.flex"
{ return (CLASS); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 142 "cool.flex"
{ return (ELSE); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 143 "cool.flex"
{ return (FI); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 144 "cool.flex"
{ return (IF); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 145 "cool.flex"
{ return (IN); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 146 "cool.flex"
{ return (INHERITS); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 147 "cool.flex"
{ return (LET); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 148 "cool.flex"
{ return (LOOP); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 149 "cool.flex"
{ return (POOL); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 150 "cool.flex"
{ return (THEN); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 151 "cool.flex"
{ return (WHILE); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 152 "cool.flex"
{ return (CASE); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 153 "cool.flex"
{ return (ESAC); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 154 "cool.flex"
{ return (OF); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 155 "cool.flex"
{ return (NEW); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 156 "cool.flex"
{ return (ISVOID); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 157 "cool.flex"
{ return (NOT); } 
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 158 "cool.flex"
{ cool_yylval.boolean = true;
                  return (BOOL_CONST);
                }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 161 "cool.flex"
{ cool_yylval.boolean = false;
                  return (BOOL_CONST);
                }
	YY_BREAK
/*
  *  String constants (C syntax)
  *  Escape sequence \c is accepted for all characters c. Except for 
  *  \n \t \b \f, the result is c.
  *
  */
case 33:
YY_RULE_SETUP
#line 171 "cool.flex"
{ cool_yylval.symbol = inttable.add_string(yytext);
                  return (TYPEID);
                }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 175 "cool.flex"
{ cool_yylval.symbol = inttable.add_string(yytext);
                  return (OBJECTID);
                }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 179 "cool.flex"
{ string_buf_ptr = string_buf;
                  BEGIN(str);
                }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 183 "cool.flex"
{ BEGIN(INITIAL);
                  *string_buf_ptr = '\0';
                }
	YY_BREAK
case 37:
/* rule 37 can match eol */
YY_RULE_SETUP
#line 187 "cool.flex"
{ return (ERROR); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 189 "cool.flex"
{
                    int result;
     
                    (void) sscanf( yytext + 1, "%o", &result );
                           
                    if ( result > 0xff ) {
                        cool_yylval.error_msg = "Unescaped chars";
                        return (ERROR);
                    }
                    
                    *string_buf_ptr++ = result;
                  }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 202 "cool.flex"
{ return (ERROR); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 204 "cool.flex"
*string_buf_ptr++ = '\n';
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 205 "cool.flex"
*string_buf_ptr++ = '\t';
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 206 "cool.flex"
*string_buf_ptr++ = '\r';
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 207 "cool.flex"
*string_buf_ptr++ = '\b';
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 208 "cool.flex"
*string_buf_ptr++ = '\f';
	YY_BREAK
case 45:
/* rule 45 can match eol */
YY_RULE_SETUP
#line 210 "cool.flex"
*string_buf_ptr++ = yytext[1];
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 212 "cool.flex"
{
                   char *yptr = yytext;
                         
                   while ( *yptr ) {
                           *string_buf_ptr++ = *yptr++;
                   }
                   
                   cool_yylval.symbol = inttable.add_string(yytext); 
                   return (STR_CONST);
                }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 225 "cool.flex"
{ cool_yylval.symbol = inttable.add_string(yytext); 
                  return (INT_CONST); 
                }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 229 "cool.flex"
{ return(43); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 230 "cool.flex"
{ return(45); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 231 "cool.flex"
{ return(42); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 232 "cool.flex"
{ return(47); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 235 "cool.flex"
{ return(59); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 236 "cool.flex"
{ return(40); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 237 "cool.flex"
{ return(41); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 238 "cool.flex"
{ return(123);}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 239 "cool.flex"
{ return(125);}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 240 "cool.flex"
{ return(91); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 241 "cool.flex"
{ return(93); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 242 "cool.flex"
{ return(58); }         
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 243 "cool.flex"
{ return(46); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 244 "cool.flex"
{ return(62); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 245 "cool.flex"
{ return(60); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 247 "cool.flex"

	YY_BREAK
case 64:
/* rule 64 can match eol */
YY_RULE_SETUP
#line 248 "cool.flex"
{ curr_lineno++; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 249 "cool.flex"
{ return(ERROR); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 250 "cool.flex"
{ cool_yylval.error_msg = "Null char present.";
                  return(ERROR);
                }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 253 "cool.flex"
ECHO;
	YY_BREAK
#line 1656 "cool-lex.cc"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(str):
case YY_STATE_EOF(comment):
case YY_STATE_EOF(line_comment):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
/* %% [14.0] code to do back-up for compressed tables and set up yy_cp goes here */
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */
/* %ok-for-header */

/* %if-c++-only */
/* %not-for-header */

/* %ok-for-header */

/* %endif */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
/* %if-c-only */
static int yy_get_next_buffer (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

/* %if-c-only */
/* %not-for-header */

    static yy_state_type yy_get_previous_state (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
/* %% [15.0] code to get the start state into yy_current_state goes here */
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
/* %% [16.0] code to find the next state goes here */
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 63);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 290 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
/* %if-c-only */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
/* %endif */
/* %if-c++-only */
/* %endif */
{
	register int yy_is_jam;
    /* %% [17.0] code to find the next state, and perhaps do backing up, goes here */
	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 63;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 290 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 289);

	return yy_is_jam ? 0 : yy_current_state;
}

/* %if-c-only */

    static void yyunput (int c, register char * yy_bp )
/* %endif */
/* %if-c++-only */
/* %endif */
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

/* %% [18.0] update yylineno here */

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}
/* %if-c-only */

/* %endif */

/* %if-c-only */
#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

/* %endif */
/* %if-c++-only */
/* %endif */
{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

/* %% [19.0] update BOL and yylineno */

	return c;
}
/* %if-c-only */
#endif	/* ifndef YY_NO_INPUT */
/* %endif */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
/* %if-c-only */
    void yyrestart  (FILE * input_file )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
/* %if-c-only */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

/* %if-c-only */
static void yy_load_buffer_state  (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
/* %if-c-only */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
/* %endif */
/* %if-c++-only */
/* %endif */
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
/* %if-c-only */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* %if-c-only */

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* %endif */

/* %if-c++-only */
/* %endif */

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
/* %if-c-only */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )
/* %endif */
/* %if-c++-only */
/* %endif */

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

/* %if-c-only */

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
/* %endif */
/* %if-c++-only */
/* %endif */
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
/* %if-c-only */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/* %if-c-or-c++ */
/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
/* %if-c-only */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}
/* %endif */

/* %if-c-or-c++ */
/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
/* %if-c-only */
void yypop_buffer_state (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}
/* %endif */

/* %if-c-or-c++ */
/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
/* %if-c-only */
static void yyensure_buffer_stack (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}
/* %endif */

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

/* %if-c-only */
static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}
/* %endif */
/* %if-c++-only */
/* %endif */

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/* %if-c-only */
/* %if-reentrant */
/* %endif */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/* %if-reentrant */
/* %endif */

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

/* %endif */

/* %if-reentrant */
/* %if-bison-bridge */
/* %endif */
/* %endif if-c-only */

/* %if-c-only */
static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}
/* %endif */

/* %if-c-only SNIP! this currently causes conflicts with the c++ scanner */
/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

/* %if-reentrant */
/* %endif */
    return 0;
}
/* %endif */

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

/* %if-tables-serialization definitions */
/* %define-yytables   The name for this specific scanner's tables. */
#define YYTABLES_NAME "yytables"
/* %endif */

/* %ok-for-header */

#line 253 "cool.flex"
