#line 2 "cool-lex.cc"

#line 4 "cool-lex.cc"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

/* %not-for-header */

/* %if-c-only */
/* %if-not-reentrant */

/* %endif */
/* %endif */
/* %ok-for-header */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* %if-c++-only */
/* %endif */

/* %if-c-only */
    
/* %endif */

/* %if-c-only */

/* %endif */

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
/* %if-c-only */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>
/* %endif */

/* %if-tables-serialization */
/* %endif */
/* end standard C headers. */

/* %if-c-or-c++ */
/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* %endif */

/* %if-c++-only */
/* %endif */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* %not-for-header */

/* Returned upon end-of-file. */
#define YY_NULL 0
/* %ok-for-header */

/* %not-for-header */

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)
/* %ok-for-header */

/* %if-reentrant */
/* %endif */

/* %if-not-reentrant */

/* %endif */

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

/* %if-not-reentrant */
extern int yyleng;
/* %endif */

/* %if-c-only */
/* %if-not-reentrant */
extern FILE *yyin, *yyout;
/* %endif */
/* %endif */

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
/* %if-c-only */
	FILE *yy_input_file;
/* %endif */

/* %if-c++-only */
/* %endif */

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */

/* %if-not-reentrant */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */
/* %endif */
/* %ok-for-header */

/* %endif */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* %if-c-only Standard (non-C++) definition */

/* %if-not-reentrant */
/* %not-for-header */

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;
/* %ok-for-header */

/* %endif */

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

/* %endif */

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* %% [1.0] yytext/yyin/yyout/yy_state_type/yylineno etc. def's & init go here */

#define FLEX_DEBUG

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

/* %if-c-only Standard (non-C++) definition */

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* %endif */

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
/* %% [2.0] code to fiddle yytext and yyleng for yymore() goes here \ */\
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
/* %% [3.0] code to copy yytext_ptr to yytext[] goes here, if %array \ */\
	(yy_c_buf_p) = yy_cp;

/* %% [4.0] data tables for the DFA and the user's section 1 definitions go here */
#define YY_NUM_RULES 68
#define YY_END_OF_BUFFER 69
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[342] =
    {   0,
        0,    0,    0,    0,    0,    0,    2,    2,   69,   67,
       64,   65,   63,   34,   52,   53,   49,   47,   59,   48,
       57,   50,   46,   56,   51,   58,   62,   61,   67,   67,
       67,   67,   67,   67,   67,   67,   67,   67,   67,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       54,   63,   55,   60,   66,   45,   36,   35,   68,    8,
        6,    8,    8,    2,    3,   64,    4,    9,   59,    1,
       46,   56,   51,   11,   12,   10,   61,   32,   32,   32,
        0,   32,   32,    0,   15,   15,   16,   17,   32,   16,
       32,   32,    0,   32,   32,    0,   26,   26,   32,    0,

       32,    0,   32,    0,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   15,   33,   15,   15,   16,
       17,   33,   16,   17,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   26,   26,   33,   33,   33,   33,   33,
       33,    0,   33,   33,    0,    0,   16,    0,    0,   17,
        0,    0,   15,   60,   45,   44,   37,   38,   42,   43,
       39,   41,   40,    5,    7,    2,   32,    0,   32,    0,
        0,   32,    0,   32,    0,    0,   32,    0,   32,    0,
        0,   19,   19,   32,    0,   19,   27,   27,   29,   29,
       27,   32,    0,   32,    0,   32,    0,   33,   33,   33,

       33,   33,   33,   33,   33,   33,    0,   33,   33,   33,
       33,   33,   19,   33,   19,   33,   27,   29,   27,   29,
       33,   33,   33,   33,    0,   33,   33,    0,   33,   33,
       19,    0,    0,    0,   29,    0,    0,    0,   19,   19,
       37,   38,   24,   24,   32,    0,   24,   14,   14,   25,
       25,   14,   32,    0,   32,    0,    0,   20,   20,   21,
       21,   22,   22,   32,    0,   24,   33,   24,   33,   14,
       25,   14,   25,   33,    0,   33,   33,   33,   33,   33,
       20,   20,   21,   21,   22,   30,   30,   22,   30,   22,
       33,   33,   22,   14,   20,   25,   25,   14,   14,   21,

       14,   37,   13,   13,   32,    0,   32,    0,    0,   23,
       23,   13,   13,   31,   31,   31,   33,   33,   33,   33,
       23,   23,   13,   32,    0,   28,   28,   28,   33,   28,
       33,   28,   32,    0,   33,   33,   18,   18,   18,   18,
        0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    4,    4,    4,    4,    1,    6,
        7,    8,    9,   10,   11,   12,   13,   14,   14,   14,
       14,   14,   14,   14,   14,   15,   15,   16,   17,   18,
       19,   20,    4,   21,   22,   23,   24,   25,   26,   27,
       23,   28,   29,   23,   23,   30,   23,   31,   32,   33,
       23,   34,   35,   36,   37,   38,   39,   23,   23,   23,
        4,   40,    4,    4,   41,    4,   42,   43,   44,   45,

       46,   47,   48,   49,   50,   48,   48,   51,   48,   52,
       53,   54,   48,   55,   56,   57,   58,   59,   60,   48,
       48,   48,   61,   62,   63,   64,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[66] =
    {   0,
        1,    1,    2,    1,    3,    1,    1,    1,    1,    1,
        1,    1,    1,    4,    4,    1,    1,    1,    1,    1,
        1,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    3,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[349] =
    {   0,
        0,    0,   63,   64,   67,   68,  247,  245,  241,  984,
      214,  984,  984,  984,  207,  984,  204,  984,  200,  193,
      984,  984,   63,  187,  185,   61,  179,  156,    0,   57,
       51,   55,   62,   69,   74,   63,   59,   83,   88,  137,
      176,   93,  178,  174,  191,  193,  185,   94,  180,  194,
      984,  235,  984,   94,  984,    0,  984,  984,  257,  984,
      984,  145,  141,    0,  984,  144,  984,  984,   88,  984,
       68,   80,   77,  984,  984,  984,   71,    0,  189,  212,
      254,  196,  237,  271,    0,  984,    0,  241,   95,  270,
      258,  269,  285,  263,  282,  298,    0,  984,  273,  292,

      187,  249,  278,  301,  322,    0,  327,  362,  350,  365,
      353,  368,  357,  369,  363,    0,  366,    0,  367,    0,
      371,  364,    0,  372,  378,  386,  400,  399,  404,  297,
      402,  403,  410,    0,    0,  407,  415,  424,  417,  425,
      418,  447,  445,  449,  446,  453,  984,  468,  461,  457,
      480,  482,  523,   24,    0,  984,  115,  120,  984,  984,
      984,  984,  984,  984,  984,    0,  501,  502,  494,  504,
      542,  508,  541,  547,  550,  569,  555,  560,  469,  543,
      582,    0,  984,  545,  556,  557,    0,  984,    0,  984,
      984,  470,  495,  571,  585,  570,  590,  599,  592,  600,

      594,  612,  615,  614,  619,  595,  629,  630,  627,  617,
      641,  637,    0,  639,    0,  642,    0,    0,    0,    0,
      604,  654,  657,  652,  656,  663,  671,  680,  677,  678,
      984,  692,  695,  694,  701,  714,  725,  674,  984,  764,
      124,  126,    0,  984,  712,  715,  724,    0,  984,    0,
      984,  984,  727,  730,  741,  743,  772,    0,  984,    0,
      984,    0,  984,  752,  778,    0,  767,    0,  774,    0,
        0,    0,    0,  785,  786,  787,  745,  792,  791,  806,
        0,    0,    0,    0,    0,    0,  984,    0,    0,  984,
      793,  811,  812,  808,  984,  815,  810,  984,  807,  825,

      849,  128,    0,  984,  830,  831,  851,  857,  865,    0,
      984,    0,    0,    0,  984,    0,  838,  861,  862,  864,
        0,    0,  872,  871,  878,    0,  984,  880,  882,    0,
      884,    0,  894,  895,  896,  897,    0,  984,    0,    0,
      984,  959,  963,  967,   81,  971,  975,  979
    } ;

static yyconst flex_int16_t yy_def[349] =
    {   0,
      341,    1,  342,  342,  343,  343,  344,  344,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  341,
       40,   40,   40,   40,   40,   40,   40,   40,   40,   40,
      341,  341,  341,  341,  341,  346,  341,  341,  347,  341,
      341,  341,  341,  348,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  345,  345,  345,
      341,  345,  345,  341,  345,  341,  345,  345,  345,  341,
      345,  345,  341,  345,  345,  341,  345,  341,  345,  341,

      345,  341,  345,  341,   40,   40,  105,  105,   40,   40,
      105,  105,   40,   40,  105,  105,   40,   40,  341,  105,
      105,  105,   40,   40,   40,  105,  105,   40,   40,  105,
      105,   40,   40,  105,   40,  105,   40,  105,  105,   40,
       40,  341,  105,   40,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  346,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  348,  345,  341,  345,  341,
      341,  345,  341,  345,  341,  341,  345,  341,  345,  341,
      341,  345,  341,  345,  341,  341,  345,  341,  345,  341,
      341,  345,  341,  345,  341,  345,  341,  105,  105,   40,

       40,  105,  105,   40,   40,  105,  341,   40,  105,  105,
       40,   40,  105,  105,   40,   40,  105,  105,   40,   40,
      105,   40,  105,  105,  341,   40,   40,  341,  105,   40,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  345,  341,  345,  341,  341,  345,  341,  345,
      341,  341,  345,  341,  345,  341,  341,  345,  341,  345,
      341,  345,  341,  345,  341,  105,  105,   40,   40,  105,
      105,   40,   40,  105,  341,   40,  105,  105,   40,   40,
      105,   40,  105,   40,  105,  105,  341,   40,   40,  341,
      105,   40,  341,  341,  341,  341,  341,  341,  341,  341,

      341,  341,  345,  341,  345,  341,  345,  341,  341,  345,
      341,  105,   40,  105,  341,   40,  105,  105,   40,   40,
      105,   40,  341,  345,  341,  345,  341,  341,  105,  105,
       40,   40,  345,  341,  105,   40,  345,  341,  105,   40,
        0,  341,  341,  341,  341,  341,  341,  341
    } ;

static yyconst flex_int16_t yy_nxt[1050] =
    {   0,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       20,   21,   22,   23,   23,   24,   25,   26,   27,   13,
       28,   29,   29,   30,   29,   31,   32,   29,   33,   34,
       35,   36,   37,   29,   29,   38,   29,   29,   39,   13,
       13,   40,   40,   41,   40,   42,   43,   40,   40,   44,
       45,   46,   47,   48,   40,   40,   49,   40,   40,   50,
       51,   52,   53,   54,   55,   57,   57,   58,   58,   61,
       61,   74,   62,   62,   63,   63,   71,   71,   79,   75,
       82,   71,   71,   85,   78,   83,   80,  154,   87,   97,
       99,   77,   88,   73,   91,   72,   89,   69,   79,   94,

       92,   82,   59,   59,   85,   95,   83,   80,   87,   97,
      101,   99,   84,   88,   91,  103,   86,   89,   81,   94,
      100,   92,  111,   90,   98,  136,   95,  112,  241,  242,
       93,  101,  179,  242,  242,   96,  103,  302,  242,  242,
      242,  242,  242,  113,  102,   66,  137,  165,  114,  104,
      105,  105,  164,  179,   84,  100,  180,  154,  105,  105,
      105,  105,  105,  105,  105,  105,  105,  105,  105,  105,
      105,  105,  105,  105,  105,  105,   77,  105,  106,  106,
      106,  106,  106,  106,  106,  106,  106,  106,  106,  106,
      106,  106,  106,  106,  106,  106,  106,  107,   76,  115,

      120,   73,   72,   70,  121,  108,  116,  138,  122,   69,
       68,  134,  194,  139,   67,   66,  126,  109,  130,  117,
      123,  143,  127,  167,  131,  124,  110,  118,  140,  125,
      172,  135,  194,  169,  141,   90,  128,   81,  132,  119,
      341,  142,  144,  129,  167,  133,   98,   65,  195,   65,
      168,  172,   93,  169,   96,  104,  145,  173,  174,  341,
      146,  147,  148,   86,  149,  150,  151,  341,  177,  152,
      157,  158,  341,  170,  195,  170,  145,  341,  174,  341,
      146,  147,  341,  148,   86,  149,  150,  151,  168,  177,
      152,  341,  175,  182,  195,  170,  153,  178,  175,  159,

      184,  187,  178,  160,  192,  173,  196,  180,  161,  168,
      195,  162,  175,  163,  182,  171,  185,  189,  178,  183,
      183,  184,  187,  193,  188,  192,  173,  196,  180,  197,
      185,  181,  176,  190,  193,  217,  188,  185,  189,  197,
      341,  183,  341,  190,  193,  341,  186,  341,  341,  341,
      197,  341,  341,  193,  190,  341,  217,  188,  188,  191,
      341,  198,  197,  105,  105,  105,  105,  105,  105,  105,
      105,  105,  105,  105,  105,  105,  105,  105,  105,  105,
      105,  105,  198,  199,  198,  341,  199,  202,  168,  203,
      203,  202,  206,  341,  341,  206,  207,  341,  209,  209,

      341,  210,  341,  199,  341,  200,  201,  341,  202,  203,
      205,  168,  204,  206,  173,  210,  208,  207,  173,  209,
      211,  213,  210,  170,  207,  180,  170,  207,  207,  175,
      175,  214,  178,  178,  213,  214,  212,  218,  221,  180,
      341,  217,  213,  341,  341,  218,  221,  183,  341,  223,
      223,  341,  214,  224,  224,  215,  216,  341,  218,  221,
      183,  185,  219,  190,  188,  185,  220,  222,  193,  223,
      226,  190,  195,  229,  224,  227,  193,  229,  225,  225,
      168,  341,  170,  225,  178,  195,  195,  341,  183,  341,
      341,  188,  195,  195,  229,  173,  197,  341,  230,  260,

      255,  168,  170,  175,  225,  178,  197,  168,  228,  183,
      197,  234,  188,  195,  231,  190,  173,  197,  178,  180,
      260,  255,  233,  175,  261,  341,  243,  244,  245,  232,
      256,  261,  234,  248,  341,  341,  190,  341,  246,  341,
      180,  235,  341,  236,  237,  261,  243,  244,  195,  245,
      178,  197,  341,  248,  234,  246,  261,  238,  239,  246,
      180,  188,  244,  244,  237,  246,  249,  244,  195,  249,
      250,  178,  197,  251,  256,  234,  246,  258,  238,  239,
      253,  180,  188,  341,  240,  254,  249,  244,  259,  259,
      250,  341,  251,  251,  249,  256,  341,  246,  258,  264,

      253,  262,  249,  247,  256,  254,  259,  254,  251,  259,
      259,  251,  251,  256,  249,  263,  254,  259,  259,  265,
      264,  254,  262,  341,  266,  266,  267,  254,  267,  274,
      252,  265,  263,  283,  256,  341,  263,  270,  271,  270,
      265,  341,  271,  257,  266,  268,  263,  267,  278,  269,
      274,  265,  277,  246,  283,  246,  275,  270,  271,  272,
      244,  244,  273,  275,  274,  261,  277,  341,  278,  278,
      341,  281,  277,  249,  281,  249,  251,  286,  256,  341,
      251,  287,  341,  283,  275,  276,  279,  285,  254,  280,
      275,  275,  281,  285,  341,  282,  286,  286,  256,  298,

      259,  287,  254,  259,  284,  287,  291,  291,  285,  341,
      263,  341,  341,  287,  288,  261,  289,  287,  263,  298,
      249,  265,  263,  261,  263,  287,  259,  291,  292,  246,
      261,  263,  287,  259,  341,  298,  341,  251,  265,  265,
      249,  290,  265,  263,  261,  256,  303,  259,  251,  304,
      246,  261,  341,  293,  259,  295,  294,  251,  304,  246,
      305,  341,  295,  306,  341,  341,  256,  303,  251,  307,
      304,  308,  341,  304,  341,  296,  304,  310,  317,  304,
      246,  305,  341,  341,  306,  304,  297,  251,  306,  299,
      307,  306,  308,  300,  263,  256,  259,  310,  246,  317,

      308,  312,  308,  311,  308,  306,  306,  251,  312,  299,
      314,  315,  314,  311,  300,  263,  256,  259,  321,  246,
      318,  308,  312,  311,  317,  301,  306,  341,  304,  313,
      314,  315,  316,  309,  318,  304,  321,  311,  321,  311,
      306,  318,  304,  308,  304,  319,  315,  315,  315,  341,
      311,  341,  306,  308,  311,  320,  322,  311,  324,  325,
      341,  306,  341,  304,  308,  304,  329,  308,  306,  304,
      311,  304,  311,  311,  311,  326,  308,  308,  341,  324,
      325,  327,  306,  304,  341,  330,  311,  329,  330,  327,
      329,  325,  325,  325,  311,  326,  327,  341,  308,  325,

      325,  327,  341,  306,  304,  330,  333,  341,  332,  327,
      323,  331,  327,  334,  325,  334,  327,  335,  327,  335,
      341,  325,  327,  325,  341,  327,  328,  333,  337,  338,
      339,  339,  334,  328,  334,  341,  334,  341,  335,  334,
      336,  334,  341,  334,  341,  334,  341,  341,  341,  337,
      338,  339,  340,  341,  341,  338,  338,  338,  338,   56,
       56,   56,   56,   60,   60,   60,   60,   64,   64,   64,
       64,  155,  341,  341,  155,  156,  156,  156,  156,  166,
      341,  166,  166,    9,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,

      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341
    } ;

static yyconst flex_int16_t yy_chk[1050] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    3,    4,    3,    4,    5,
        6,   26,    5,    6,    5,    6,   23,   23,   30,   26,
       31,   71,   71,   32,  345,   31,   30,  154,   33,   36,
       37,   77,   33,   73,   34,   72,   33,   69,   30,   35,

       34,   31,    3,    4,   32,   35,   31,   30,   33,   36,
       38,   37,   31,   33,   34,   39,   32,   33,   30,   35,
       37,   34,   42,   33,   36,   48,   35,   42,  157,  157,
       34,   38,   89,  158,  158,   35,   39,  241,  241,  242,
      242,  302,  302,   42,   38,   66,   48,   63,   42,   39,
       40,   40,   62,   89,   42,   48,   89,   54,   40,   40,
       40,   40,   40,   40,   40,   40,   40,   40,   40,   40,
       40,   40,   40,   40,   40,   40,   28,   40,   40,   40,
       40,   40,   40,   40,   40,   40,   40,   40,   40,   40,
       40,   40,   40,   40,   40,   40,   40,   41,   27,   43,

       44,   25,   24,   20,   44,   41,   43,   49,   44,   19,
       17,   47,  101,   49,   15,   11,   45,   41,   46,   43,
       44,   50,   45,   79,   46,   44,   41,   43,   49,   44,
       82,   47,  101,   80,   49,   44,   45,   41,   46,   43,
        9,   49,   50,   45,   79,   46,   47,    8,  101,    7,
       79,   82,   45,   80,   46,   50,   52,   82,   83,    0,
       52,   52,   52,   52,   52,   52,   52,    0,   88,   52,
       59,   59,    0,   80,  102,   81,   52,    0,   83,    0,
       52,   52,    0,   52,   52,   52,   52,   52,   81,   88,
       52,    0,   84,   91,  102,   81,   52,   90,   83,   59,

       92,   94,   88,   59,   99,   84,  103,   90,   59,   81,
      102,   59,   84,   59,   91,   81,   93,   95,   90,   91,
       93,   92,   94,  100,   94,   99,   84,  103,   90,  104,
       92,   90,   84,   96,   99,  130,   96,   93,   95,  103,
        0,   93,    0,   95,  100,    0,   93,    0,    0,    0,
      104,    0,    0,  100,   96,    0,  130,   96,  130,   96,
        0,  107,  104,  105,  105,  105,  105,  105,  105,  105,
      105,  105,  105,  105,  105,  105,  105,  105,  105,  105,
      105,  105,  107,  108,  109,    0,  110,  111,  107,  112,
      114,  113,  115,    0,    0,  117,  119,    0,  121,  124,

        0,  122,    0,  108,    0,  109,  110,    0,  111,  112,
      114,  109,  113,  115,  111,  125,  117,  119,  113,  121,
      124,  126,  122,  108,  115,  122,  110,  117,  119,  112,
      114,  127,  121,  124,  128,  129,  125,  131,  136,  125,
        0,  132,  126,    0,    0,  133,  137,  126,    0,  138,
      140,    0,  127,  139,  141,  128,  129,    0,  131,  136,
      128,  127,  132,  131,  132,  129,  133,  137,  136,  138,
      140,  133,  142,  143,  139,  141,  137,  144,  139,  141,
      145,    0,  149,  142,  150,  138,  140,    0,  146,    0,
        0,  146,  142,  148,  143,  149,  148,    0,  144,  192,

      179,  145,  149,  152,  142,  150,  143,  145,  142,  146,
      144,  151,  146,  148,  146,  151,  149,  148,  150,  152,
      192,  179,  149,  152,  193,    0,  167,  168,  169,  148,
      179,  192,  151,  172,    0,    0,  151,    0,  170,    0,
      152,  151,    0,  152,  153,  193,  167,  168,  153,  169,
      153,  153,    0,  172,  153,  169,  193,  153,  153,  170,
      153,  153,  167,  168,  153,  170,  173,  171,  153,  172,
      174,  153,  153,  175,  180,  153,  171,  184,  153,  153,
      177,  153,  153,    0,  153,  178,  173,  171,  185,  186,
      174,    0,  176,  175,  176,  180,    0,  171,  184,  196,

      177,  194,  173,  171,  180,  178,  184,  181,  174,  185,
      186,  175,  176,  181,  176,  195,  177,  185,  186,  197,
      196,  178,  194,    0,  198,  200,  199,  181,  201,  206,
      176,  196,  194,  221,  181,    0,  195,  202,  203,  204,
      197,    0,  205,  181,  198,  200,  195,  199,  210,  201,
      206,  197,  209,  199,  221,  201,  206,  202,  203,  204,
      198,  200,  205,  207,  208,  221,  211,    0,  212,  210,
        0,  214,  209,  202,  216,  204,  203,  224,  210,    0,
      205,  225,    0,  222,  207,  208,  211,  223,  209,  212,
      207,  208,  214,  226,    0,  216,  227,  224,  212,  238,

      214,  225,  211,  216,  222,  228,  229,  230,  223,    0,
      228,    0,    0,  224,  226,  222,  227,  225,  223,  238,
      233,  232,  232,  234,  226,  228,  234,  229,  230,  233,
      235,  228,  227,  235,    0,  238,    0,  236,  229,  230,
      233,  228,  232,  232,  234,  236,  245,  234,  237,  246,
      233,  235,    0,  232,  235,  234,  233,  236,  247,  237,
      253,    0,  235,  254,    0,    0,  236,  245,  237,  255,
      246,  256,    0,  245,    0,  236,  246,  264,  277,  247,
      237,  253,    0,    0,  254,  247,  237,  240,  253,  240,
      255,  254,  256,  240,  240,  240,  240,  264,  240,  277,

      257,  267,  255,  265,  256,  257,  277,  240,  269,  240,
      274,  275,  276,  264,  240,  240,  240,  240,  291,  240,
      278,  257,  267,  265,  279,  240,  257,    0,  267,  269,
      274,  275,  276,  257,  280,  269,  292,  293,  291,  265,
      299,  278,  294,  296,  297,  279,  274,  275,  276,    0,
      300,    0,  279,  278,  291,  280,  292,  293,  305,  306,
        0,  299,    0,  294,  296,  297,  317,  280,  299,  294,
      300,  297,  292,  293,  301,  307,  296,  301,    0,  305,
      306,  308,  301,  301,    0,  318,  300,  317,  320,  309,
      319,  305,  306,  309,  301,  307,  323,    0,  301,  317,

      323,  308,    0,  301,  301,  318,  324,    0,  320,  309,
      301,  319,  307,  325,  309,  328,  323,  329,  308,  331,
        0,  323,  318,  319,    0,  320,  309,  324,  333,  334,
      335,  336,  324,  323,  325,    0,  328,    0,  329,  325,
      331,  328,    0,  329,    0,  331,    0,    0,    0,  333,
      334,  335,  336,    0,    0,  333,  334,  335,  336,  342,
      342,  342,  342,  343,  343,  343,  343,  344,  344,  344,
      344,  346,    0,    0,  346,  347,  347,  347,  347,  348,
        0,  348,  348,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,

      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 1;

static yyconst flex_int16_t yy_rule_linenum[68] =
    {   0,
      137,  138,  139,  145,  146,  147,  152,  159,  160,  169,
      170,  171,  176,  177,  178,  179,  180,  181,  182,  183,
      184,  185,  186,  187,  188,  189,  190,  191,  192,  193,
      196,  206,  210,  214,  218,  224,  235,  248,  250,  251,
      252,  253,  254,  256,  258,  268,  272,  273,  274,  275,
      278,  279,  280,  281,  282,  283,  284,  285,  286,  287,
      288,  289,  292,  298,  300,  302,  306
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "cool.flex"
/*
%%
 *  The scanner definition for COOL.
 */
/*
 *  Stuff enclosed in %{ %} in the first section is copied verbatim to the
 *  output, so headers and global definitions are placed here to be visible
 * to the code in the file.  Don't remove anything that was here initially
 */
#line 12 "cool.flex"
#include <cool-parse.h>
#include <stringtab.h>
#include <utilities.h>
#include <math.h>
/* The compiler assumes these identifiers. */
#define yylval cool_yylval
#define yylex  cool_yylex

/* Max size of string constants */
#define MAX_STR_CONST 1025
#define YY_NO_UNPUT   /* keep g++ happy */

extern FILE *fin; /* we read from this file */

/* define YY_INPUT so we read from the FILE fin:
 * This change makes it possible to use this scanner in
 * the Cool compiler.
 */
#undef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( (result = fread( (char*)buf, sizeof(char), max_size, fin)) < 0) \
		YY_FATAL_ERROR( "read() in flex scanner failed");

char string_buf[MAX_STR_CONST]; /* to assemble string constants */
char *string_buf_ptr;

int nested_level = 0;

extern int curr_lineno;
extern int verbose_flag;

extern YYSTYPE cool_yylval;

/*
 *  Add Your own definitions here
 */




/*
 * Define names for regular expressions here.
 */
#line 950 "cool-lex.cc"

#define INITIAL 0
#define str 1
#define comment 2
#define line_comment 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
/* %if-c-only */
#include <unistd.h>
/* %endif */
/* %if-c++-only */
/* %endif */
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* %if-c-only Reentrant structure and macros (non-C++). */
/* %if-reentrant */
/* %if-c-only */

static int yy_init_globals (void );

/* %endif */
/* %if-reentrant */
/* %endif */
/* %endif End reentrant structures and macros. */

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* %if-bison-bridge */
/* %endif */

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

/* %not-for-header */

    static void yyunput (int c,char *buf_ptr  );
    
/* %ok-for-header */

/* %endif */

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT
/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif
/* %ok-for-header */

/* %endif */
#endif

/* %if-c-only */

/* %endif */

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* %if-c-only Standard (non-C++) definition */
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
/* %endif */
/* %if-c++-only C++ definition */
/* %endif */
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
/* %% [5.0] fread()/read() definition of YY_INPUT goes here unless we're doing C++ \ */\
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\
/* %if-c++-only C++ definition \ */\
/* %endif */

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
/* %if-c-only */
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
/* %endif */
/* %if-c++-only */
/* %endif */
#endif

/* %if-tables-serialization structures and prototypes */
/* %not-for-header */

/* %ok-for-header */

/* %not-for-header */

/* %tables-yydmap generated elements */
/* %endif */
/* end tables serialization structures and prototypes */

/* %ok-for-header */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1
/* %if-c-only Standard (non-C++) definition */

extern int yylex (void);

#define YY_DECL int yylex (void)
/* %endif */
/* %if-c++-only C++ definition */
/* %endif */
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

/* %% [6.0] YY_RULE_SETUP definition goes here */
#define YY_RULE_SETUP \
	YY_USER_ACTION

/* %not-for-header */

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
/* %% [7.0] user's declarations go here */
#line 132 "cool.flex"

 /*
  *  Nested comments
  */

#line 1206 "cool-lex.cc"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
/* %if-c-only */
			yyin = stdin;
/* %endif */
/* %if-c++-only */
/* %endif */

		if ( ! yyout )
/* %if-c-only */
			yyout = stdout;
/* %endif */
/* %if-c++-only */
/* %endif */

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
/* %% [8.0] yymore()-related code goes here */
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

/* %% [9.0] code to set up and find next match goes here */
		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 342 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 984 );

yy_find_action:
/* %% [10.0] code to find the action number goes here */
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

/* %% [11.0] code for yylineno update goes here */

do_action:	/* This label is used only to access EOF actions. */

/* %% [12.0] debug code goes here */
		if ( yy_flex_debug )
			{
			if ( yy_act == 0 )
				fprintf( stderr, "--scanner backing up\n" );
			else if ( yy_act < 68 )
				fprintf( stderr, "--accepting rule at line %ld (\"%s\")\n",
				         (long)yy_rule_linenum[yy_act], yytext );
			else if ( yy_act == 68 )
				fprintf( stderr, "--accepting default rule (\"%s\")\n",
				         yytext );
			else if ( yy_act == 69 )
				fprintf( stderr, "--(end of buffer or a NUL)\n" );
			else
				fprintf( stderr, "--EOF (start condition %d)\n", YY_START );
			}

		switch ( yy_act )
	{ /* beginning of action switch */
/* %% [13.0] actions go here */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 137 "cool.flex"
BEGIN(line_comment);
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 138 "cool.flex"
/* eat up anything thats not a newline */
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 139 "cool.flex"
{ curr_lineno++;
                          BEGIN(INITIAL);
                        }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 145 "cool.flex"
{ BEGIN(comment);}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 146 "cool.flex"
{ nested_level++; }
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 147 "cool.flex"
curr_lineno++;
	YY_BREAK
case YY_STATE_EOF(comment):
#line 148 "cool.flex"
{ cool_yylval.error_msg = "EOF in comment";
                          BEGIN(INITIAL);
                          return(ERROR);
                        }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 152 "cool.flex"
{ if (nested_level > 0) {
                            nested_level--; 
                          } else {
                            BEGIN(INITIAL);
                          }
                        }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 159 "cool.flex"
{}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 160 "cool.flex"
{ cool_yylval.error_msg = "Unmatched *)";
                          return (ERROR);
                        }
	YY_BREAK
/*
  *  The multiple-character operators.
  */
case 10:
YY_RULE_SETUP
#line 169 "cool.flex"
{ return (DARROW); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 170 "cool.flex"
{ return (ASSIGN); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 171 "cool.flex"
{ return (LE); }
	YY_BREAK
/*
  * Keywords are case-insensitive except for the values true and false,
  * which must begin with a lower-case letter.
  */
case 13:
YY_RULE_SETUP
#line 176 "cool.flex"
{ return (CLASS); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 177 "cool.flex"
{ return (ELSE); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 178 "cool.flex"
{ return (FI); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 179 "cool.flex"
{ return (IF); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 180 "cool.flex"
{ return (IN); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 181 "cool.flex"
{ return (INHERITS); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 182 "cool.flex"
{ return (LET); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 183 "cool.flex"
{ return (LOOP); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 184 "cool.flex"
{ return (POOL); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 185 "cool.flex"
{ return (THEN); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 186 "cool.flex"
{ return (WHILE); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 187 "cool.flex"
{ return (CASE); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 188 "cool.flex"
{ return (ESAC); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 189 "cool.flex"
{ return (OF); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 190 "cool.flex"
{ return (NEW); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 191 "cool.flex"
{ return (ISVOID); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 192 "cool.flex"
{ return (NOT); } 
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 193 "cool.flex"
{ cool_yylval.boolean = true;
                  return (BOOL_CONST);
                }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 196 "cool.flex"
{ cool_yylval.boolean = false;
                  return (BOOL_CONST);
                }
	YY_BREAK
/*
  *  String constants (C syntax)
  *  Escape sequence \c is accepted for all characters c. Except for 
  *  \n \t \b \f, the result is c.
  *
  */
case 32:
YY_RULE_SETUP
#line 206 "cool.flex"
{ cool_yylval.symbol = inttable.add_string(yytext);
                  return (TYPEID);
                }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 210 "cool.flex"
{ cool_yylval.symbol = inttable.add_string(yytext);
                  return (OBJECTID);
                }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 214 "cool.flex"
{ string_buf_ptr = string_buf;
                  BEGIN(str);
                }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 218 "cool.flex"
{ BEGIN(INITIAL);
                  *string_buf_ptr = '\0';
                  cool_yylval.symbol = inttable.add_string(string_buf);
                  return(STR_CONST);
                }
	YY_BREAK
case 36:
/* rule 36 can match eol */
YY_RULE_SETUP
#line 224 "cool.flex"
{ cool_yylval.error_msg = "Unterminated string constant";
                  BEGIN(INITIAL);
                  return (ERROR); 
                }
	YY_BREAK
case YY_STATE_EOF(str):
#line 229 "cool.flex"
{ cool_yylval.error_msg = "EOF in string constant";
                  BEGIN(INITIAL);
                  *string_buf_ptr = '\0';
                  return(ERROR);
                }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 235 "cool.flex"
{
                    int result;
     
                    (void) sscanf( yytext + 1, "%o", &result );
                           
                    if ( result > 0xff ) {
                        cool_yylval.error_msg = "Unescaped chars";
                        return (ERROR);
                    }
                    
                    *string_buf_ptr++ = result;
                  }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 248 "cool.flex"
{ return (ERROR); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 250 "cool.flex"
*string_buf_ptr++ = '\n';
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 251 "cool.flex"
*string_buf_ptr++ = '\t';
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 252 "cool.flex"
*string_buf_ptr++ = '\r';
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 253 "cool.flex"
*string_buf_ptr++ = '\b';
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 254 "cool.flex"
*string_buf_ptr++ = '\f';
	YY_BREAK
case 44:
/* rule 44 can match eol */
YY_RULE_SETUP
#line 256 "cool.flex"
*string_buf_ptr++ = yytext[1];
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 258 "cool.flex"
{    
                   char *yptr = yytext;
                   
                   while ( *yptr ) {
                           *string_buf_ptr++ = *yptr++;
                   }
                }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(line_comment):
#line 266 "cool.flex"
{ yyterminate(); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 268 "cool.flex"
{ cool_yylval.symbol = inttable.add_string(yytext); 
                  return (INT_CONST); 
                }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 272 "cool.flex"
{ return(43); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 273 "cool.flex"
{ return(45); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 274 "cool.flex"
{ return(42); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 275 "cool.flex"
{ return(47); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 278 "cool.flex"
{ return(59); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 279 "cool.flex"
{ return(40); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 280 "cool.flex"
{ return(41); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 281 "cool.flex"
{ return(123);}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 282 "cool.flex"
{ return(125);}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 283 "cool.flex"
{ return(58); }         
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 284 "cool.flex"
{ return(46); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 285 "cool.flex"
{ return(60); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 286 "cool.flex"
{ return(44); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 287 "cool.flex"
{ return(126);}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 288 "cool.flex"
{ return(64); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 289 "cool.flex"
{ return(61); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 292 "cool.flex"
{ cool_yylval.error_msg = yytext;
                  return(ERROR);
                }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 298 "cool.flex"

	YY_BREAK
case 65:
/* rule 65 can match eol */
YY_RULE_SETUP
#line 300 "cool.flex"
{ curr_lineno++; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 302 "cool.flex"
{ cool_yylval.error_msg = "Null char present.";
                  return(ERROR);
                }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 306 "cool.flex"
{ cool_yylval.error_msg = yytext;
                  return(ERROR);
                }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 309 "cool.flex"
ECHO;
	YY_BREAK
#line 1749 "cool-lex.cc"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
/* %% [14.0] code to do back-up for compressed tables and set up yy_cp goes here */
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */
/* %ok-for-header */

/* %if-c++-only */
/* %not-for-header */

/* %ok-for-header */

/* %endif */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
/* %if-c-only */
static int yy_get_next_buffer (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

/* %if-c-only */
/* %not-for-header */

    static yy_state_type yy_get_previous_state (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
/* %% [15.0] code to get the start state into yy_current_state goes here */
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
/* %% [16.0] code to find the next state goes here */
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 65);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 342 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
/* %if-c-only */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
/* %endif */
/* %if-c++-only */
/* %endif */
{
	register int yy_is_jam;
    /* %% [17.0] code to find the next state, and perhaps do backing up, goes here */
	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 65;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 342 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 341);

	return yy_is_jam ? 0 : yy_current_state;
}

/* %if-c-only */

    static void yyunput (int c, register char * yy_bp )
/* %endif */
/* %if-c++-only */
/* %endif */
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

/* %% [18.0] update yylineno here */

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}
/* %if-c-only */

/* %endif */

/* %if-c-only */
#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

/* %endif */
/* %if-c++-only */
/* %endif */
{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

/* %% [19.0] update BOL and yylineno */

	return c;
}
/* %if-c-only */
#endif	/* ifndef YY_NO_INPUT */
/* %endif */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
/* %if-c-only */
    void yyrestart  (FILE * input_file )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
/* %if-c-only */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

/* %if-c-only */
static void yy_load_buffer_state  (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
/* %if-c-only */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
/* %endif */
/* %if-c++-only */
/* %endif */
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
/* %if-c-only */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* %if-c-only */

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* %endif */

/* %if-c++-only */
/* %endif */

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
/* %if-c-only */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )
/* %endif */
/* %if-c++-only */
/* %endif */

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

/* %if-c-only */

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
/* %endif */
/* %if-c++-only */
/* %endif */
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
/* %if-c-only */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/* %if-c-or-c++ */
/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
/* %if-c-only */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}
/* %endif */

/* %if-c-or-c++ */
/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
/* %if-c-only */
void yypop_buffer_state (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}
/* %endif */

/* %if-c-or-c++ */
/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
/* %if-c-only */
static void yyensure_buffer_stack (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}
/* %endif */

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

/* %if-c-only */
static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}
/* %endif */
/* %if-c++-only */
/* %endif */

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/* %if-c-only */
/* %if-reentrant */
/* %endif */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/* %if-reentrant */
/* %endif */

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

/* %endif */

/* %if-reentrant */
/* %if-bison-bridge */
/* %endif */
/* %endif if-c-only */

/* %if-c-only */
static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}
/* %endif */

/* %if-c-only SNIP! this currently causes conflicts with the c++ scanner */
/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

/* %if-reentrant */
/* %endif */
    return 0;
}
/* %endif */

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

/* %if-tables-serialization definitions */
/* %define-yytables   The name for this specific scanner's tables. */
#define YYTABLES_NAME "yytables"
/* %endif */

/* %ok-for-header */

#line 309 "cool.flex"
